import type { Species } from './pet-breeds';

export type HillsDisease='gastrointestinal'|'pancreatitis'|'urinary'|'kidney';
export type HillsProduct={id:string;species:Species;series:string;seriesName:string;productCode:string;productName:string;form:'dry'|'wet'|'both';indications:string[];features:string[];feedingNotes:string[];contraindications:string[];wetForm?:string;source:string};
const source='用户粘贴的《希尔斯处方粮湿粮手册_扣子版》整理稿（重复段已去重；正文在犬用l/d条目中途截断，需以当地最新官方包装及兽医意见复核）';

export const hillsProducts:HillsProduct[]=[
 {id:'hills-canine-gi-biome',species:'dog',series:'肠胃微生态',seriesName:'Digestive Care / Biome',productCode:'i/d Biome',productName:'肠胃微生态处方粮',form:'both',indications:['慢性腹泻','抗菌药相关性腹泻','急性肠炎恢复期','菌群失调','IBD维持期'],features:['ActivBiome+益生元纤维技术（具体原料以包装为准）','支持短链脂肪酸生成','高消化率蛋白','可溶与不可溶纤维','Omega-3','抗氧化营养'],feedingNotes:['整理稿建议慢性腹泻至少使用3-4周后评估','合并胰腺炎时需先确认是否应选择低脂配方','湿粮有助增加总水分'],contraindications:['严重胰腺炎或需严格限脂时不可自行替代i/d Low Fat'],wetForm:'肉块/肉泥罐头',source},
 {id:'hills-canine-gi-lowfat',species:'dog',series:'低脂肠胃',seriesName:'Low Fat Digestive',productCode:'i/d Low Fat',productName:'低脂肠胃处方粮',form:'both',indications:['犬胰腺炎营养管理','淋巴管扩张','高脂血症','蛋白丢失性肠病','需要限脂的胆道疾病'],features:['低脂配方（实际干物质值需核对包装）','高消化率蛋白','MCT','可溶性纤维','Omega-3','维生素支持'],feedingNotes:['急性胰腺炎的进食时机和方式必须由兽医按呕吐、疼痛和水合状态决定，不执行固定禁食24-48小时规则','慢性使用期限需复诊评估','湿粮可增加水分和适口性'],contraindications:['需要高能量密度但无法达到热量目标的宠物'],wetForm:'肉块罐头',source},
 {id:'hills-canine-gi-digestive',species:'dog',series:'肠胃护理',seriesName:'Digestive Care',productCode:'i/d Digestive Care',productName:'肠胃护理处方粮',form:'both',indications:['急性呕吐/腹泻恢复期','胃肠炎','消化不良','IBD维持期'],features:['高消化率','可溶性纤维','Omega-3','电解质支持'],feedingNotes:['整理稿建议至少2-3周后评估，实际期限按病因和复诊决定'],contraindications:['严重胰腺炎或需严格限脂时'],wetForm:'肉泥罐头',source},
 {id:'hills-canine-urinary',species:'dog',series:'泌尿道护理',seriesName:'Urinary Care',productCode:'c/d Multicare',productName:'泌尿道护理处方粮',form:'both',indications:['犬鸟粪石管理','草酸钙结石风险管理','尿路感染辅助管理'],features:['控制镁磷钙','促进尿液稀释','Omega-3','抗氧化营养'],feedingNotes:['必须先确认结石/晶体类型和尿路感染情况','长期预防期间需尿检和影像复查'],contraindications:['生长幼犬','未知结石类型时自行使用','用泌尿配方替代肾病处方'],wetForm:'肉块罐头',source},
 {id:'hills-canine-urinary-dissolution',species:'dog',series:'泌尿道溶解',seriesName:'Urinary Dissolution',productCode:'s/d',productName:'泌尿道溶解处方粮',form:'both',indications:['经兽医确认的犬鸟粪石急性溶解'],features:['针对尿液环境的短期配方','低镁策略','蛋白和矿物质调整','促进饮水策略'],feedingNotes:['整理稿标注最长12周，必须由兽医安排尿液pH和影像复查','溶解后是否转c/d由复查决定'],contraindications:['幼犬','怀孕或哺乳犬','高蛋白需求状态','未确认鸟粪石时使用'],wetForm:'罐头',source},
 {id:'hills-canine-renal',species:'dog',series:'肾脏护理',seriesName:'Renal Care',productCode:'k/d',productName:'肾脏护理处方粮',form:'both',indications:['犬CKD营养管理','部分肾小球疾病营养支持','合并高血压的肾病营养管理'],features:['控制磷（具体数值需确认是原物还是干物质）','适量高利用率蛋白','Omega-3','酸碱与维生素支持','钠调整'],feedingNotes:['CKD分期和水合稳定后由兽医评估','湿粮有助增加总水分，但需结合心脏状态','不要用普通犬粮大量稀释处方配方','连续监测体重、血磷、肌酐和SDMA'],contraindications:['非肾性疾病造成的高蛋白或特殊营养需求'],wetForm:'肉块/肉泥罐头',source},
];

const terms:Record<HillsDisease,RegExp>={gastrointestinal:/肠胃|胃肠|腹泻|消化|IBD/i,pancreatitis:/胰腺|低脂|高脂血症/i,urinary:/泌尿|结石|膀胱|鸟粪石/i,kidney:/肾病|肾脏|CKD|肾衰/i};
export function inferHillsDisease(text:string):HillsDisease|null{return(Object.keys(terms) as HillsDisease[]).find(x=>terms[x].test(text))||null}
export function recommendHills(species:Species,text:string){const disease=inferHillsDisease(text);return disease?hillsProducts.filter(x=>x.species===species&&x.indications.some(i=>terms[disease].test(i))):[]}
export function findHillsProduct(text:string){const q=text.toLowerCase();return hillsProducts.find(x=>q.includes(x.productCode.toLowerCase())||q.includes(x.productName.toLowerCase()))||null}
export function answerHillsQuestion(question:string){if(!/希尔斯|Hill'?s/i.test(question))return null;const species:Species=/猫|猫咪/.test(question)?'cat':'dog';const matches=recommendHills(species,question);if(!matches.length)return species==='cat'?'当前粘贴内容没有实际提供完整猫用希尔斯产品条目，因此不能按目录声称的13款编造型号。请补充猫用手册正文或包装资料。':'当前粘贴内容中没有找到该疾病对应的完整犬用希尔斯条目；正文在l/d处截断，请补充后再推荐。';return matches.map(x=>`【Hill's ${x.productCode}｜${x.productName}】\n适用方向：${x.indications.join('、')}。\n主要特点：${x.features.join('、')}。\n喂养注意：${x.feedingNotes.join('；')}。\n禁忌：${x.contraindications.join('、')}。${x.wetForm?`\n湿粮形态：${x.wetForm}。`:''}`).join('\n\n')+'\n\n这份粘贴稿没有提供可核验的代谢能和体重喂量表，因此不能计算准确克数；请补充包装热量、体重、BCS和每日干湿粮型号。';}
