type Species='cat'|'dog';
type Stage={stage:number;range:string;meaning:string};
export type IndicatorInterpretation={text:string;sourceTitle:string};
function read(text:string,labels:string[]){for(const label of labels){const m=text.match(new RegExp(`${label}[^0-9]{0,12}(\\d+(?:\\.\\d+)?)`,'i'));if(m)return Number(m[1]);}return undefined;}
function creatinine(species:Species,v:number):Stage{if(species==='cat')return v<140?{stage:1,range:'<140',meaning:'非氮质血症'}:v<=250?{stage:2,range:'140-250',meaning:'轻度氮质血症'}:v<=440?{stage:3,range:'251-440',meaning:'中度氮质血症'}:{stage:4,range:'>440',meaning:'重度氮质血症'};return v<125?{stage:1,range:'<125',meaning:'非氮质血症'}:v<=250?{stage:2,range:'125-250',meaning:'轻度氮质血症'}:v<=440?{stage:3,range:'251-440',meaning:'中度氮质血症'}:{stage:4,range:'>440',meaning:'重度氮质血症'};}
function sdma(species:Species,v:number):Stage{const c=species==='cat'?[18,25,38]:[18,35,54];return v<c[0]?{stage:1,range:`<${c[0]}`,meaning:'未达到升级阈值'}:v<=c[1]?{stage:2,range:`${c[0]}-${c[1]}`,meaning:'对应Stage 2'}:v<=c[2]?{stage:3,range:`${c[1]+1}-${c[2]}`,meaning:'对应Stage 3'}:{stage:4,range:`>${c[2]}`,meaning:'对应Stage 4'};}
function upc(species:Species,v:number){const borderline=species==='cat'?0.4:0.5;return v<.2?`UP/C ${v}：阴性（<0.2）`:v<=borderline?`UP/C ${v}：边界蛋白尿（${species==='cat'?'猫0.2-0.4':'犬0.2-0.5'}）`:`UP/C ${v}：蛋白尿（>${borderline}）`}
function pressure(v:number){return v<140?`SBP ${v} mmHg：正常`:v<160?`SBP ${v} mmHg：高血压前期（140-159）`:v<180?`SBP ${v} mmHg：高血压（160-179）`:`SBP ${v} mmHg：重度高血压（≥180）`;}
export function interpretIrisIndicators(question:string):IndicatorInterpretation|undefined{
 const rawCrea=read(question,['肌酐','CREA','creatinine']);const crea=rawCrea!==undefined&&/mg\s*\/\s*dL/i.test(question)?Math.round(rawCrea*88.4):rawCrea;const sd=read(question,['SDMA']);const ratio=read(question,['UP\\s*/\\s*C','UPC','尿蛋白肌酐比']);const bp=read(question,['SBP','收缩压','血压']);const hct=read(question,['HCT','红细胞压积']);if([crea,sd,ratio,bp,hct].every(v=>v===undefined))return;
 const species:Species|undefined=/犬|狗/.test(question)?'dog':/猫/.test(question)?'cat':undefined;const list:Species[]=species?[species]:['cat','dog'];const lines:string[]=[];const stages:string[]=[];const risks:string[]=[];
 for(const s of list){const name=s==='cat'?'猫':'犬';if(crea!==undefined){const x=creatinine(s,crea);lines.push(`- ${name}肌酐 ${crea} μmol/L：Stage ${x.stage}（${x.range} μmol/L），${x.meaning}。`);stages.push(`${name}按肌酐约Stage ${x.stage}`);}if(sd!==undefined){const x=sdma(s,sd);lines.push(`- ${name} SDMA ${sd} μg/dL：Stage ${x.stage}（${x.range} μg/dL），${x.meaning}。`);stages.push(`${name}按SDMA约Stage ${x.stage}`);}if(ratio!==undefined){const x=upc(s,ratio);risks.push(`- ${x}${ratio>(s==='cat'?.4:.5)?'，提示进展风险并需确认持续性':''}`);}}
 if(bp!==undefined)risks.push(`- ${pressure(bp)}；≥160时靶器官损伤风险升高。`);
 if(hct!==undefined){for(const s of list){const name=s==='cat'?'猫':'犬';const threshold=s==='cat'?25:30;risks.push(`- ${name} HCT ${hct}%：${hct<threshold?`低于IRIS关注阈值${threshold}%，需评估CKD相关贫血并排除失血、感染等原因`:`未低于${threshold}%治疗关注阈值，但需结合症状和连续趋势`}`);}}
 const stageSummary=stages.length?`${stages.join('；')}。${species?'':'未说明物种，以上同时列出猫犬阈值，请补充物种后确认单一分期。'}`:'当前只提供了亚分期或并发症指标，不能单独确定CKD Stage；还需要肌酐和/或SDMA。';
 const used=[species?`物种：${species==='cat'?'猫':'犬'}`:'物种：未说明',crea!==undefined?`肌酐：${crea} μmol/L`:null,sd!==undefined?`SDMA：${sd} μg/dL`:null,ratio!==undefined?`UP/C：${ratio}`:null,bp!==undefined?`SBP：${bp} mmHg`:null,hct!==undefined?`HCT：${hct}%`:null].filter(Boolean).join('；');
 const sources=[crea!==undefined||sd!==undefined?(species==='cat'?'【CKD-CAT-022】猫CKD主分期':species==='dog'?'【CKD-DOG-023】犬CKD主分期':'【CKD-CAT-022/CKD-DOG-023】猫犬主分期'):null,ratio!==undefined?(species==='cat'?'【CKD-CAT-024】猫UP/C亚分期':species==='dog'?'【CKD-DOG-025】犬UP/C亚分期':'【CKD-CAT-024/CKD-DOG-025】猫犬UP/C亚分期'):null,bp!==undefined?'【CKD-BP-026】血压亚分期':null].filter(Boolean).join(' · ');
 return {sourceTitle:sources,text:`📌 本次使用的用户数据\n${used}\n\n📊 指标解读\n${lines.join('\n')}\n${risks.join('\n')}\n\n📋 分期判断\n${stageSummary}\n\n⚠️ 风险评估\n肌酐和SDMA应在稳定补水状态下重复确认；若SDMA持续对应更高阶段，需按更高风险进一步评估。UP/C蛋白尿、SBP升高和贫血会增加整体管理风险。\n\n💡 管理建议\n带上肌酐、SDMA、BUN、血磷、钙钾、尿比重、UP/C、血压、HCT、体重和肌肉趋势，按连续变化讨论饮食、复查和是否需要进一步检查。不要自行调整药物、补液或剂量。\n\n🏥 就医建议\n请与兽医讨论CKD诊断依据、是否需要重复化验、蛋白尿是否持续、血压是否需要复测或干预，以及贫血、电解质、超声等检查。\n\n📌 这个分析基于 IRIS 公开资料，诊断和用药方案需要由兽医确认。`};
}
