import type { Species } from './pet-breeds';

export type RoyalDisease='gastrointestinal'|'pancreatitis'|'urinary'|'kidney'|'liver'|'diabetes'|'allergy';
export type RoyalProduct={id:string;name:string;species:Species;disease:RoyalDisease;form:'dry'|'wet'|'both';productCode:string;indications:string[];features:string[];nutrition?:{protein?:number;fat?:number;fiber?:number;phosphorus?:number;calcium?:number;kcalPer100g?:number};feedingGuide:string;contraindications:string[];wetPairing?:string;transitionGuide?:string;source:string};

const source='用户上传的《皇家兽医处方粮知识库》整理稿（附件内容截至 canine-skin 条目处截断；产品信息需以购买地最新官方包装和兽医意见复核）';
export const royalCaninProducts:RoyalProduct[]=[
 {id:'canine-gi',name:'Gastrointestinal 肠胃处方粮',species:'dog',disease:'gastrointestinal',form:'both',productCode:'干粮5110/湿粮5114',indications:['急性/慢性胃肠炎','消化不良','吸收不良','肠胃敏感','结肠炎','腹泻恢复期'],features:['高消化率蛋白质和碳水化合物','FOS/MOS益生元','EPA/DHA','MCT易吸收能量'],nutrition:{protein:25,fat:18,fiber:4.5,kcalPer100g:390},feedingGuide:'整理稿建议急性期至少3-4周；长期使用时需兽医复评。',contraindications:[],wetPairing:'整理稿称GI湿粮与GI干粮可混合使用。',source},
 {id:'canine-gi-low-fat',name:'Gastrointestinal Low Fat 低脂肠胃处方粮',species:'dog',disease:'pancreatitis',form:'both',productCode:'干粮5130/湿粮5134',indications:['胰腺炎','高脂血症','淋巴管扩张症','脂肪不耐受'],features:['低脂配方','高消化率蛋白','FOS和甜菜粕','EPA/DHA'],nutrition:{protein:28,fat:14,fiber:5.5,kcalPer100g:340},feedingGuide:'整理稿建议胰腺炎管理至少3个月，期限由兽医按病程确定。',contraindications:['高脂食物','普通零食','高脂人食'],wetPairing:'整理稿称湿粮脂肪更低，实际需核对罐体保证分析值和干物质换算。',source},
 {id:'canine-urinary-so',name:'Urinary S/O 泌尿道处方粮',species:'dog',disease:'urinary',form:'both',productCode:'干粮5120/湿粮5124',indications:['鸟粪石管理','草酸钙结石风险管理','特发性膀胱炎','尿路感染辅助管理'],features:['促进尿液稀释','调整尿液环境','控制镁钙磷','Omega-3支持'],nutrition:{protein:24,fat:16,calcium:.7,phosphorus:.6,kcalPer100g:370},feedingGuide:'必须先确认结石类型；整理稿建议鸟粪石溶解管理5-12周，随后复查。',contraindications:['未知结石类型时自行使用','用泌尿粮代替肾病处方粮'],wetPairing:'湿粮有助增加总水分，但仍需记录饮水和尿量。',source},
 {id:'canine-urinary-uc',name:'Urinary U/C Low Purine 低嘌呤泌尿道处方粮',species:'dog',disease:'urinary',form:'dry',productCode:'干粮5136',indications:['尿酸盐/尿酸结石','高尿酸血症','嘌呤代谢异常'],features:['低嘌呤','调整尿液环境','限制蛋白来源'],nutrition:{protein:16,fat:22,kcalPer100g:385},feedingGuide:'长期使用需监测尿液pH、尿酸和结石变化。',contraindications:['草酸钙结石','猫使用','未确认结石类型时自行使用'],source},
 {id:'canine-renal',name:'Renal 肾脏处方粮',species:'dog',disease:'kidney',form:'both',productCode:'干粮5132/湿粮5135',indications:['犬CKD IRIS 2-4期','肾小球疾病','尿毒症营养管理'],features:['低磷','适量高利用率蛋白','EPA/DHA','抗氧化复合物','酸碱支持'],nutrition:{protein:21,fat:20,phosphorus:.18,calcium:.4,kcalPer100g:395},feedingGuide:'整理稿建议犬CKD 2期后评估使用；必须结合血磷、食欲、体重和兽医方案。',contraindications:['高蛋白高磷食物','高盐食物','用泌尿S/O代替肾病处方'],wetPairing:'湿粮可增加水分和适口性，心脏病或补液限制犬需兽医确认总水分。',transitionGuide:'整理稿建议约7天渐进过渡，拒食或胃肠不适时应放慢并联系兽医。',source},
 {id:'canine-early-renal',name:'Early Renal 早期肾脏处方粮',species:'dog',disease:'kidney',form:'dry',productCode:'干粮5142',indications:['犬CKD IRIS 1-2期','老年犬肾脏营养支持'],features:['较Renal更高蛋白和磷但低于普通粮','Omega-3','抗氧化剂'],nutrition:{protein:24,phosphorus:.3,kcalPer100g:390},feedingGuide:'整理稿建议早期评估；进展后需由兽医依据复查决定是否转Renal。',contraindications:['把早期配方用于需要更严格限磷的阶段而不复查'],transitionGuide:'转换产品时整理稿建议约7天过渡。',source},
 {id:'canine-hepatic',name:'Hepatic 肝脏处方粮',species:'dog',disease:'liver',form:'dry',productCode:'干粮5126',indications:['肝功能障碍','肝性脑病','门脉短路','慢性肝炎','铜蓄积性肝病'],features:['高消化率蛋白','控制铜','添加锌','MCT','BCAA'],nutrition:{protein:23,fat:18,kcalPer100g:360},feedingGuide:'使用期限和蛋白水平需结合肝病类型、血氨和兽医复查。',contraindications:['高铜食物','未经评估的高脂食物'],source},
 {id:'canine-diabetic',name:'Diabetic 糖尿病处方粮',species:'dog',disease:'diabetes',form:'both',productCode:'干粮5122/湿粮5128',indications:['犬糖尿病','胰岛素抵抗','高血糖管理'],features:['低升糖碳水策略','高蛋白','高纤维','L-肉碱'],nutrition:{protein:38,fat:15,fiber:10.8,kcalPer100g:330},feedingGuide:'需与兽医确定的胰岛素和固定餐次配合；拒食时先联系兽医确认当次用药。',contraindications:['高糖食物','普通零食','随意改变餐次和摄入量'],wetPairing:'整理稿称湿粮适用于食欲不稳，但必须核对实际摄入并与胰岛素方案同步。',source},
 {id:'canine-hydrolyzed',name:'Hydrolyzed Protein 水解蛋白低敏处方粮',species:'dog',disease:'allergy',form:'both',productCode:'干粮5125/湿粮5129',indications:['食物不良反应','食物不耐受','IBD辅助管理','慢性瘙痒鉴别'],features:['水解蛋白','单一纯化碳水来源','排除常见过敏原','高消化率'],feedingGuide:'排除饮食试验通常需严格执行6-8周并由兽医复评。',contraindications:['试验期间任何其他食物或零食','未经兽医确认频繁换粮'],source},
];

const diseaseTerms:Record<RoyalDisease,RegExp>={gastrointestinal:/肠胃|胃肠|腹泻|消化/,pancreatitis:/胰腺|低脂|高脂血症/,urinary:/泌尿|结石|膀胱|尿酸|鸟粪石/,kidney:/肾病|肾脏|CKD|肾衰/i,liver:/肝病|肝脏|肝炎|门脉/,diabetes:/糖尿病|高血糖|胰岛素/,allergy:/过敏|低敏|水解|IBD|瘙痒/i};
export function inferRoyalDisease(text:string):RoyalDisease|null{return(Object.keys(diseaseTerms) as RoyalDisease[]).find(x=>diseaseTerms[x].test(text))||null}
export function recommendRoyalCanin(species:Species,text:string){const disease=inferRoyalDisease(text);return disease?royalCaninProducts.filter(x=>x.species===species&&x.disease===disease):[]}
export function findRoyalProduct(text:string){const q=text.toLowerCase();return royalCaninProducts.find(x=>q.includes(x.name.toLowerCase())||q.includes(x.name.split(' ')[0].toLowerCase())||q.includes(x.productCode))||null}
export function estimateDailyGrams(product:RoyalProduct,weightKg:number,energyFactor=.9){if(!product.nutrition?.kcalPer100g||!(weightKg>0))return null;const kcal=Math.round(70*Math.pow(weightKg,.75)*energyFactor);return{kcal,grams:Math.round(kcal/product.nutrition.kcalPer100g*100),formula:`70 × ${weightKg}^0.75 × ${energyFactor} ÷ ${product.nutrition.kcalPer100g} × 100`}}

export function answerRoyalCaninQuestion(question:string){if(!/皇家|Royal Canin|处方粮|处方湿粮|一天.{0,4}(喂|吃).{0,4}(克|多少)|干湿粮|换粮|零食/i.test(question))return null;const species:Species=/猫|猫咪/.test(question)?'cat':'dog';const disease=inferRoyalDisease(question);if(!disease)return null;const matches=recommendRoyalCanin(species,question);if(!matches.length)return species==='cat'?'您上传的附件没有包含完整猫用皇家处方粮条目，因此我不能根据这份资料编造具体型号。请补充猫用官方手册或包装资料，再结合疾病、分期、体重、BCS和兽医诊断选择。':'附件中没有找到与该病种匹配且完整的犬用条目，请补充完整官方手册。';const weight=Number(question.match(/(\d+(?:\.\d+)?)\s*(?:kg|公斤|千克)/i)?.[1]);return matches.map(product=>{const estimate=weight?estimateDailyGrams(product,weight):null;return`【${product.name}｜${product.productCode}】\n适用方向：${product.indications.join('、')}。\n核心特点：${product.features.join('、')}。\n${product.wetPairing?`干湿搭配：${product.wetPairing}\n`:''}${product.transitionGuide?`换粮：${product.transitionGuide}\n`:''}禁忌：${product.contraindications.length?product.contraindications.join('、'):'需遵循包装及兽医要求'}。\n${estimate?`按附件能量值的初步估算约${estimate.grams}g/日（约${estimate.kcal}kcal），这不是处方克数，需按绝育状态、活动量、BCS、湿粮热量和兽医目标修正。`:'如需估算克数，请补充当前体重、BCS、每日湿粮型号和包装代谢能。'}`}).join('\n\n');}
