'use client';
import { useEffect,useRef,useState } from 'react';
import { ArrowLeft,Building2,CheckCircle2,FileBadge2,LockKeyhole,ShieldCheck,Stethoscope,Upload,UserRound } from 'lucide-react';
import { Card,PageTitle,Pill,SectionTitle } from './ui';

type Role='owner'|'hospital'|'doctor'|'developer';
type Application={role:'hospital'|'doctor';name:string;phone:string;organization:string;licenseNo:string;credentialFiles:string[];status:'待平台审核';submittedAt:string};
type AccountState={phone:string;wechat:string;applications:Application[]};
const KEY='petcare-account-role-center-v1';
const empty:AccountState={phone:'',wechat:'',applications:[]};
const input='mt-2 w-full rounded-xl border border-[#d7e2dc] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#4c8b6d]';

export function AccountRoleCenter({back}:{back:()=>void}){
 const [role,setRole]=useState<Role>('owner');const [account,setAccount]=useState<AccountState>(empty);const [saved,setSaved]=useState('');
 const [application,setApplication]=useState({name:'',phone:'',organization:'',licenseNo:''});const [files,setFiles]=useState<string[]>([]);const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{setAccount(JSON.parse(localStorage.getItem(KEY)||JSON.stringify(empty)))}catch{setAccount(empty)}},[]);
 const persist=(next:AccountState,message:string)=>{setAccount(next);localStorage.setItem(KEY,JSON.stringify(next));setSaved(message)};
 const submit=()=>{if((role!=='hospital'&&role!=='doctor')||!application.name.trim()||!application.phone.trim()||!application.organization.trim()||!application.licenseNo.trim()||!files.length)return;const item:Application={role,name:application.name.trim(),phone:application.phone.trim(),organization:application.organization.trim(),licenseNo:application.licenseNo.trim(),credentialFiles:files,status:'待平台审核',submittedAt:new Date().toISOString()};persist({...account,applications:[item,...account.applications]},'资质申请已存档，当前状态：待平台审核');setApplication({name:'',phone:'',organization:'',licenseNo:''});setFiles([])};
 const currentApplications=account.applications.filter(x=>x.role===role);
 return <><PageTitle title="账号与资质申请" subtitle="这里只申请访问权限；宠主端、医院/医生端和开发者端分别独立使用" action={<button onClick={back} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm"><ArrowLeft size={16}/>返回</button>}/>
 <Card className="mb-4 border-[#d4e4da] bg-[#f4faf6] p-4 text-sm leading-6 text-[#52675b]"><ShieldCheck className="mr-2 inline text-[#287656]" size={18}/><b>权限原则：</b>注册账号默认只有宠主权限；医院营业资质和执业兽医资格必须由平台人工核验。上传证件不等于审核通过，开发者权限只能由后台管理员授予。</Card>
 <div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{([['owner','宠主资料',UserRound],['hospital','申请医院端',Building2],['doctor','申请医生端',Stethoscope],['developer','开发者说明',LockKeyhole]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>{setRole(id);setSaved('')}} className={`flex min-h-20 flex-col items-center justify-center gap-2 rounded-xl border text-sm ${role===id?'border-[#397c5e] bg-[#e6f2eb] font-semibold text-[#226849]':'bg-white text-[#64756c]'}`}><Icon size={20}/>{label}</button>)}</div>
 {saved&&<Card className="mb-4 border-[#9bc9ad] bg-[#eff9f3] p-4 text-sm"><CheckCircle2 className="mr-2 inline text-[#287656]" size={18}/>{saved}</Card>}
 {role==='owner'&&<Card className="p-5 sm:p-6"><SectionTitle>宠主账号资料</SectionTitle><p className="text-sm leading-6 text-[#6c7b73]">宠主注册后使用宠物档案、健康记录、AI管家、提醒和医院消息。当前静态版资料仅保存在这台设备。</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">手机号<input value={account.phone} onChange={e=>setAccount({...account,phone:e.target.value})} inputMode="tel" placeholder="请输入本人手机号" className={input}/></label><label className="text-sm font-semibold">微信号（选填）<input value={account.wechat} onChange={e=>setAccount({...account,wechat:e.target.value})} placeholder="用于后续绑定微信登录" className={input}/></label></div><button onClick={()=>persist(account,'宠主账号资料已保存在本机')} disabled={!account.phone.trim()} className="mt-5 rounded-xl bg-[#287656] px-5 py-3 text-sm font-semibold text-white disabled:bg-gray-300">保存宠主资料</button><p className="mt-4 text-xs leading-5 text-[#74827a]">短信验证码、微信授权登录和跨设备同步必须接入正式认证后台后启用；当前不会发送验证码。</p></Card>}
 {(role==='hospital'||role==='doctor')&&<div className="grid gap-4 lg:grid-cols-[1fr_360px]"><Card className="p-5 sm:p-6"><SectionTitle>{role==='hospital'?'申请医院版':'申请医生版'}</SectionTitle><p className="text-sm leading-6 text-[#6c7b73]">{role==='hospital'?'医院版用于管理本院已授权客户、随访任务、医生团队和医院消息。':'医生版用于查看本人获授权病例、下发护理执行单、回复宠主消息和核对异常记录。'}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">{role==='hospital'?'负责人姓名':'兽医姓名'}<input value={application.name} onChange={e=>setApplication({...application,name:e.target.value})} className={input}/></label><label className="text-sm font-semibold">本人手机号<input value={application.phone} onChange={e=>setApplication({...application,phone:e.target.value})} inputMode="tel" className={input}/></label><label className="text-sm font-semibold">{role==='hospital'?'医院全称':'执业医院'}<input value={application.organization} onChange={e=>setApplication({...application,organization:e.target.value})} className={input}/></label><label className="text-sm font-semibold">{role==='hospital'?'统一社会信用代码/许可证号':'执业兽医资格证号'}<input value={application.licenseNo} onChange={e=>setApplication({...application,licenseNo:e.target.value})} className={input}/></label></div><button onClick={()=>fileRef.current?.click()} className="mt-5 flex items-center gap-2 rounded-xl border border-[#bfd4c8] bg-[#f5faf7] px-4 py-2.5 text-sm font-semibold text-[#2c7053]"><Upload size={17}/>选择资质证明照片</button><input ref={fileRef} type="file" accept="image/*,.pdf" multiple className="hidden" onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,5).map(x=>x.name))}/>{files.length>0&&<p className="mt-2 text-xs leading-5 text-[#6e7d75]">已选择：{files.join('、')}</p>}<button onClick={submit} disabled={!application.name.trim()||!application.phone.trim()||!application.organization.trim()||!application.licenseNo.trim()||!files.length} className="mt-5 w-full rounded-xl bg-[#287656] py-3 font-semibold text-white disabled:bg-gray-300">提交平台人工审核</button><p className="mt-3 text-xs leading-5 text-[#74827a]">静态版只保存证件文件名，不上传证件内容。正式版需加密上传、限制审核员权限、保留审计日志并设置资料保留期限。</p></Card><Card className="h-fit p-5"><SectionTitle>我的申请</SectionTitle>{currentApplications.length?currentApplications.map((x,i)=><div key={`${x.submittedAt}-${i}`} className="mb-3 rounded-xl bg-[#f5f8f6] p-3 text-sm"><div className="flex justify-between gap-2"><b>{x.organization}</b><Pill tone="amber">{x.status}</Pill></div><p className="mt-2 text-xs leading-5 text-[#728078]">{x.name} · {x.licenseNo}<br/>{new Date(x.submittedAt).toLocaleString('zh-CN',{hour12:false})}</p></div>):<div className="py-10 text-center text-sm text-[#7a8880]"><FileBadge2 className="mx-auto mb-3"/>尚未提交申请</div>}</Card></div>}
 {role==='developer'&&<Card className="p-6"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-[#edf0ef]"><LockKeyhole/></span><div><h2 className="font-bold">开发者后台不开放自助申请</h2><p className="mt-2 text-sm leading-6 text-[#66776e]">开发者可以管理知识库版本、审核医院和医生、配置商品、查看客服工单和系统审计，但不能默认查看全部宠主病历。访问必须由服务端管理员账号、双重验证和权限日志控制。</p><p className="mt-3 rounded-xl bg-[#fff7e8] p-3 text-sm leading-6 text-[#805f2b]">当前静态版没有安全的开发者登录能力，因此不会提供“点一下进入后台”的假入口。接入 Supabase Auth 和角色权限后再开放。</p></div></div></Card>}
 </>;
}
