'use client';
import { useEffect,useState } from 'react';
import { AlertTriangle,ArrowLeft,CalendarDays,Check,ChevronRight,Clock3,FileSignature,History,Plus,ShieldCheck,Stethoscope,Users } from 'lucide-react';
import { collectPetCareContext } from '@/lib/care-workflow';
import { getActiveCarePlan,getPendingCarePlan,loadAuditEvents,loadCaregivers,loadFollowupOutcomes,loadTaskCompletions,saveCaregivers,saveTaskCompletion,type CareTask,type SignedCarePlan } from '@/lib/care-coordination';
import { navigateToFeature } from '@/lib/app-navigation';
import { usePetProfile } from './pet-profile-context';
import { Card,PageTitle,Pill,SectionTitle } from './ui';

const todayKey=()=>new Date().toISOString().slice(0,10);

export function CarePlanWorkspace({back}:{back:()=>void}){
 const {profile}=usePetProfile();const [refresh,setRefresh]=useState(0);const [ready,setReady]=useState(false);const [caregiver,setCaregiver]=useState('我');const [caregivers,setCaregivers]=useState<string[]>(['我']);const [newCaregiver,setNewCaregiver]=useState('');
 useEffect(()=>{setReady(true);const list=loadCaregivers(profile.id);setCaregivers(list);setCaregiver(list[0]||'我')},[profile.id,refresh]);
 const context=ready?collectPetCareContext(profile.id):null;const plan=ready?getActiveCarePlan(profile.id):null;const pending=ready?getPendingCarePlan(profile.id):null;const completions=ready?loadTaskCompletions(profile.id).filter(x=>x.date===todayKey()):[];const outcomes=ready?loadFollowupOutcomes(profile.id):[];const audits=ready?loadAuditEvents(profile.id).slice(0,8):[];
 const completedIds=new Set(completions.filter(x=>x.status==='completed').map(x=>x.taskId));const progress=plan?.tasks.length?Math.round(completedIds.size/plan.tasks.length*100):0;
 const complete=(task:CareTask)=>{if(!plan)return;saveTaskCompletion({petId:profile.id,planId:plan.id,planVersion:plan.version,taskId:task.id,taskTitle:task.title,date:todayKey(),status:completedIds.has(task.id)?'skipped':'completed',caregiver,note:''});setRefresh(x=>x+1)};
 const addCaregiver=()=>{if(!newCaregiver.trim())return;const next=saveCaregivers(profile.id,[...caregivers,newCaregiver]);setCaregivers(next);setCaregiver(newCaregiver.trim());setNewCaregiver('')};
 return <div className="space-y-5"><PageTitle title="今日院后护理" subtitle={plan?`${profile.name} · 主治医生签署方案 v${plan.version}`:`${profile.name} · 等待主治医生签署护理方案`} action={<button onClick={back} className="flex items-center gap-2 rounded-xl border border-[#d7e2dc] bg-white px-3 py-2 text-sm"><ArrowLeft size={16}/>返回首页</button>}/>
  {!plan?<NoSignedPlan profileName={profile.name} hasDoctor={Boolean(profile.doctor&&profile.hospital)}/>:<>
   <PlanAuthority plan={plan} pending={pending}/>
   <section className="overflow-hidden rounded-[24px] border border-[#cfe2d8] bg-white"><div className="bg-[linear-gradient(135deg,#e8f6ee,#f7fbf8)] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-[#2b7657]">今天由 {caregiver} 执行</p><h2 className="mt-1 text-2xl font-bold">{plan.tasks.length}项护理任务</h2><p className="mt-2 text-sm text-[#66786f]">基础方案始终可见；健康记录只用于调整风险提醒，不会擅自改动医嘱。</p></div><div className="relative grid size-16 shrink-0 place-items-center rounded-2xl bg-white text-[#287656] shadow-sm"><strong className="text-lg">{progress}%</strong></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-[#2c7a59] transition-all" style={{width:`${progress}%`}}/></div></div>
    <div className="divide-y divide-[#e6ece8]">{plan.tasks.map(task=><TaskRow key={task.id} task={task} done={completedIds.has(task.id)} onToggle={()=>complete(task)}/>)}</div>
   </section>
   <CaregiverPanel caregiver={caregiver} setCaregiver={setCaregiver} caregivers={caregivers} newCaregiver={newCaregiver} setNewCaregiver={setNewCaregiver} addCaregiver={addCaregiver}/>
   <div className="grid gap-4 lg:grid-cols-2"><TodayStatus context={context} plan={plan}/><OutcomePanel outcomes={outcomes}/></div>
   <Card className="p-5"><SectionTitle>方案边界和联系规则</SectionTitle><div className="grid gap-3 md:grid-cols-2"><InfoBlock icon={ShieldCheck} title="AI允许做什么" text={plan.aiScope}/><InfoBlock icon={AlertTriangle} title="必须联系医生" text={plan.contactRules}/></div></Card>
   <Card className="p-5"><SectionTitle>护理留痕</SectionTitle>{audits.length?<div className="mt-2 divide-y divide-[#e5ebe7]">{audits.map(x=><div key={x.id} className="flex gap-3 py-3 text-sm"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#4a8c6d]"/><div className="min-w-0 flex-1"><b>{x.action}</b><p className="mt-1 text-[#66776e]">{x.detail}</p><small className="mt-1 block text-[#89948e]">{x.actor} · {new Date(x.at).toLocaleString('zh-CN',{hour12:false})}</small></div></div>)}</div>:<p className="text-sm text-[#718078]">尚无执行记录。</p>}</Card>
  </>}
 </div>;
}

function NoSignedPlan({profileName,hasDoctor}:{profileName:string;hasDoctor:boolean}){return <Card className="p-7 sm:p-9"><div className="mx-auto max-w-xl text-center"><span className="mx-auto grid size-16 place-items-center rounded-[22px] bg-[#e8f4ed] text-[#287656]"><FileSignature size={30}/></span><h2 className="mt-5 text-xl font-bold">等待主治医生签署方案</h2><p className="mt-2 text-sm leading-7 text-[#66776e]">宠馨智不会用通用模板冒充{profileName}的医嘱。医生签署后，方案即使当天没有打卡也会显示；AI只负责拆解、提醒、记录和风险分流。</p><div className="mt-5 rounded-xl bg-[#f5f8f6] p-4 text-left text-sm leading-6 text-[#52655a]"><b>{hasDoctor?'已记录主治医院和医生':'尚未完成医院/医生绑定'}</b><p className="mt-1">请由已授权医院在医生端选择该病例并签署护理方案。</p></div><button onClick={()=>navigateToFeature('profile')} className="mt-5 rounded-xl bg-[#287656] px-5 py-3 text-sm font-semibold text-white">检查档案与医院授权</button></div></Card>}

function PlanAuthority({plan,pending}:{plan:SignedCarePlan;pending:SignedCarePlan|null}){return <Card className="overflow-hidden"><div className="flex flex-col gap-4 border-b border-[#e2e9e5] bg-[#f7faf8] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#e1f0e8] text-[#247050]"><Stethoscope size={21}/></span><div><b className="text-lg">{plan.doctorName} 医生已签署</b><p className="mt-1 text-sm text-[#66776e]">{plan.hospitalName} · {plan.disease} {plan.stage}</p></div></div><Pill tone="green">有效方案 v{plan.version}</Pill></div><div className="grid gap-3 p-5 sm:grid-cols-4"><PlanMeta label="开始日期" value={plan.startDate}/><PlanMeta label="复查日期" value={plan.reviewDate}/><PlanMeta label="签署时间" value={new Date(plan.signedAt).toLocaleString('zh-CN',{hour12:false})}/><PlanMeta label="修改原因" value={plan.changeReason||'首次制定'}/></div>{pending&&<div className="mx-5 mb-5 flex items-start gap-3 rounded-xl border border-[#ead5ac] bg-[#fff8e9] p-4 text-sm text-[#765622]"><CalendarDays className="mt-0.5 shrink-0" size={18}/><span><b>医生已签署 v{pending.version}</b><br/>新方案将于 {pending.effectiveFrom} 生效，当前任务今天不被突然替换。</span></div>}</Card>}
function PlanMeta({label,value}:{label:string;value:string}){return <div><span className="text-xs text-[#7a8981]">{label}</span><b className="mt-1 block text-sm">{value||'未填写'}</b></div>}

function TaskRow({task,done,onToggle}:{task:CareTask;done:boolean;onToggle:()=>void}){return <div className="flex items-start gap-4 p-5"><button onClick={onToggle} aria-label={done?'取消完成':'标记完成'} className={`mt-0.5 grid size-7 shrink-0 place-items-center rounded-lg border transition ${done?'border-[#287656] bg-[#287656] text-white':'border-[#b9cbc1] bg-white text-transparent'}`}><Check size={17}/></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className={done?'text-[#718078] line-through':''}>{task.title}</b><Pill>{task.category}</Pill></div><p className="mt-2 text-sm leading-6 text-[#596c61]">{task.instructions}</p><p className="mt-2 flex flex-wrap gap-3 text-xs text-[#7a8881]"><span className="flex items-center gap-1"><Clock3 size={13}/>{task.time}</span><span>{task.frequency}</span></p></div><ChevronRight className="mt-1 shrink-0 text-[#a0aca5]" size={18}/></div>}

function CaregiverPanel({caregiver,setCaregiver,caregivers,newCaregiver,setNewCaregiver,addCaregiver}:{caregiver:string;setCaregiver:(x:string)=>void;caregivers:string[];newCaregiver:string;setNewCaregiver:(x:string)=>void;addCaregiver:()=>void}){return <Card className="p-5"><div className="flex items-start gap-3"><Users className="mt-0.5 text-[#39795e]"/><div className="min-w-0 flex-1"><b>家庭共同护理</b><p className="mt-1 text-sm text-[#6b7c73]">每次执行都会记录是谁完成，避免重复喂药或漏做。</p><div className="mt-3 flex flex-wrap gap-2">{caregivers.map(x=><button key={x} onClick={()=>setCaregiver(x)} className={`rounded-full px-3 py-2 text-xs font-semibold ${caregiver===x?'bg-[#287656] text-white':'bg-[#edf3ef] text-[#50665a]'}`}>{x}</button>)}</div><div className="mt-3 flex max-w-md gap-2"><input value={newCaregiver} onChange={e=>setNewCaregiver(e.target.value)} placeholder="添加家人姓名" className="min-w-0 flex-1 rounded-xl border border-[#d7e1db] px-3 py-2 text-sm"/><button onClick={addCaregiver} className="flex items-center gap-1 rounded-xl border border-[#bcd2c5] px-3 text-sm font-semibold text-[#286e50]"><Plus size={15}/>添加</button></div></div></div></Card>}

function TodayStatus({context,plan}:{context:ReturnType<typeof collectPetCareContext>|null;plan:SignedCarePlan}){const today=context?.today;const risk=today?.riskAssessment;return <Card className="p-5"><SectionTitle>今日健康状态</SectionTitle>{today?<><div className="flex items-center justify-between gap-3"><Pill tone={risk?.level==='red'?'red':risk?.level==='orange'||risk?.level==='yellow'?'amber':'green'}>{risk?.label||'已完成记录'}</Pill><small className="text-[#7b8981]">{new Date(today.recordedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</small></div><p className="mt-3 text-sm leading-6 text-[#586b60]">{risk?.action||'记录已进入长期健康档案。'}</p>{risk?.reasons.map(x=><p key={x} className="mt-2 text-xs text-[#6e7d75]">· {x}</p>)}</>:<><p className="text-sm leading-6 text-[#5d6f65]">今天还没有健康记录，但医生签署的基础任务仍然有效。</p><button onClick={()=>navigateToFeature('monitor')} className="mt-4 rounded-xl bg-[#287656] px-4 py-2.5 text-sm font-semibold text-white">30秒记录今天状态</button></>}<p className="mt-4 rounded-xl bg-[#f4f7f5] p-3 text-xs leading-5 text-[#718078]">医生设置的7天变化阈值：体重下降 {plan.thresholds.weightLossPct7d}%；饮水变化 {plan.thresholds.waterChangePct7d}%。系统只提示风险，不自动改医嘱。</p></Card>}

function OutcomePanel({outcomes}:{outcomes:ReturnType<typeof loadFollowupOutcomes>}){return <Card className="p-5"><SectionTitle>复诊效果验证</SectionTitle>{outcomes.length?<div className="space-y-3">{outcomes.slice(0,2).map(x=><div key={x.id} className="rounded-xl border border-[#dce6e0] p-4"><div className="flex items-center justify-between"><b>{x.conclusion}</b><Pill>{x.reviewDate}</Pill></div><p className="mt-2 text-sm leading-6 text-[#596c61]">{x.summary}</p><p className="mt-2 text-xs text-[#7a8881]">复查指标：{x.metrics||'未填写'} · {x.doctorName}</p></div>)}</div>:<div className="rounded-xl border border-dashed border-[#cfdbd4] p-5 text-center"><History className="mx-auto text-[#7c9186]"/><p className="mt-3 text-sm text-[#6e7d75]">复诊后由医生录入结果，用指标和临床表现验证方案是否有效。</p></div>}</Card>}
function InfoBlock({icon:Icon,title,text}:{icon:typeof ShieldCheck;title:string;text:string}){return <div className="flex items-start gap-3 rounded-xl bg-[#f5f8f6] p-4"><Icon className="mt-0.5 shrink-0 text-[#39795e]" size={19}/><div><b className="text-sm">{title}</b><p className="mt-2 whitespace-pre-line text-sm leading-6 text-[#5c6e64]">{text||'由主治医生填写'}</p></div></div>}
