'use client';
import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle,ArrowLeft,Building2,CheckCircle2,ClipboardCopy,Download,FileText,MessageSquareText,ShieldCheck,ShoppingBag,Stethoscope } from 'lucide-react';
import { loadDailyCheckins } from '@/lib/daily-checkins';
import { loadSymptomLogs } from '@/lib/symptom-logs';
import { usePetProfile } from './pet-profile-context';
import { Card,PageTitle,Pill,SectionTitle } from './ui';
import { HospitalMatchWorkspace } from './hospital-match-workspace';

type RequestRecord={id:string;petId:string;need:string;description:string;hospital:string;status:'本机草稿'|'待后台同步';createdAt:string};
const key=(petId:string)=>`petcare-care-network-requests:${petId}`;

export function CareNetworkWorkspace({back}:{back:()=>void}){
 const {profile}=usePetProfile();const [need,setNeed]=useState('疑难病例咨询');const [description,setDescription]=useState('');const [records,setRecords]=useState<RequestRecord[]>([]);const [notice,setNotice]=useState('');
 const [mode,setMode]=useState<'coordination'|'match'>('coordination');
 useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem(key(profile.id))||'[]'))}catch{setRecords([])}},[profile.id]);
 const summary=useMemo(()=>buildHandoff(profile),[profile]);
 const connected=profile.careAuthorization==='verified';
 const save=()=>{if(!description.trim())return;const item:RequestRecord={id:`care-${Date.now()}`,petId:profile.id,need,description:description.trim(),hospital:profile.hospital,status:connected?'待后台同步':'本机草稿',createdAt:new Date().toISOString()};const next=[item,...records];setRecords(next);localStorage.setItem(key(profile.id),JSON.stringify(next));setDescription('');setNotice(connected?'需求已存档；当前静态版尚未连接消息后台，因此未向医院发送。':'已保存为本机草稿。绑定并核验合作医院后才能发送。')};
 const copy=async()=>{await navigator.clipboard?.writeText(summary);setNotice('转诊资料包已复制，可在就诊或联系医生时使用。')};
 const download=()=>{const blob=new Blob([summary],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${profile.name}-转诊资料包.txt`;a.click();URL.revokeObjectURL(a.href)};
 if(mode==='match')return <HospitalMatchWorkspace back={()=>setMode('coordination')}/>;
 return <div className="space-y-5"><PageTitle title="找医院与医疗协同" subtitle="没有熟悉医院时先按需求匹配，就诊后再继续院外护理" action={<button onClick={back} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm"><ArrowLeft size={16}/>返回</button>}/>
 <div className="grid gap-3 sm:grid-cols-2"><button onClick={()=>setMode('match')} className="pet-action rounded-2xl border border-[#cfe0e9] bg-[#f2f8fb] p-5 text-left"><Building2 className="text-[#3f718e]" size={22}/><b className="mt-3 block">还没有熟悉的医院</b><p className="mt-1 text-sm leading-6 text-[#66776e]">按城市、病种、医院擅长和急诊能力，从已核验入驻医院中匹配。</p><span className="mt-3 block text-sm font-semibold text-[#3f718e]">找适合的医院 →</span></button><div className="rounded-2xl border border-[#cfe2d7] bg-[#f3faf6] p-5"><Stethoscope className="text-[#287656]" size={22}/><b className="mt-3 block">已有医院或医生</b><p className="mt-1 text-sm leading-6 text-[#66776e]">管理连接、整理复诊资料，把家庭记录交给授权医生复核。</p><span className="mt-3 block text-sm font-semibold text-[#287656]">当前在协同页面</span></div></div>
 <Card className="border-[#d7e5dc] bg-[#f5faf7] p-4 text-sm leading-6 text-[#52675b]"><ShieldCheck className="mr-2 inline text-[#287656]" size={18}/><b>协同边界：</b>AI先解决知识解释和资料整理；涉及诊断、处方、剂量调整或危急情况，必须转给执业兽医。平台只展示已核验的合作医生和医院。</Card>
 <div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><Card className="p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><SectionTitle>疑难问题转诊资料包</SectionTitle><Pill>{profile.name}</Pill></div><pre className="mt-3 max-h-[480px] overflow-auto whitespace-pre-wrap rounded-xl bg-[#f4f7f5] p-4 text-xs leading-6 text-[#4f6257]">{summary}</pre><div className="mt-4 flex flex-wrap gap-2"><button onClick={copy} className="flex items-center gap-2 rounded-xl bg-[#287656] px-4 py-2.5 text-sm font-semibold text-white"><ClipboardCopy size={17}/>复制资料包</button><button onClick={download} className="flex items-center gap-2 rounded-xl border border-[#bcd1c5] px-4 py-2.5 text-sm font-semibold text-[#286d51]"><Download size={17}/>下载文件</button></div></Card>
 <div className="space-y-4"><Card className="p-5"><SectionTitle>当前医疗连接</SectionTitle><div className="mt-3 flex items-start gap-3"><Building2 className="mt-0.5 text-[#36765a]"/><div><b>{profile.hospital||'尚未填写医院'}</b><p className="mt-1 text-xs leading-5 text-[#718078]">{connected?'已验证连接，可在正式后台启用消息和预约。':profile.hospital?'用户自行记录，尚未核验合作关系。':'没有合作医院时，平台不会生成附近医院或虚假预约。'}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs">{[['线上医生咨询',connected],['线下预约挂号',connected],['医院消息',connected],['医生用药提醒',connected]].map(([x,on])=><div key={String(x)} className={`rounded-lg p-3 font-semibold ${on?'bg-[#eaf5ee] text-[#286d51]':'bg-[#f1f2f1] text-[#77827c]'}`}>{on?<CheckCircle2 className="mr-1 inline" size={14}/>:null}{x}</div>)}</div></Card>
 <Card className="p-5"><SectionTitle>创建协同需求</SectionTitle><select value={need} onChange={e=>setNeed(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-3 py-2.5 text-sm"><option>疑难病例咨询</option><option>线下就诊预约</option><option>复诊资料提交</option><option>用药问题确认</option><option>营养方案复核</option></select><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} placeholder="写清楚发生了什么、持续多久、最担心什么" className="mt-3 w-full rounded-xl border px-3 py-2.5 text-sm leading-6"/><button onClick={save} disabled={!description.trim()} className="mt-3 w-full rounded-xl bg-[#287656] py-3 text-sm font-semibold text-white disabled:bg-gray-300">保存协同需求</button>{notice&&<p className="mt-3 rounded-lg bg-[#f4f7f5] p-3 text-xs leading-5 text-[#607168]">{notice}</p>}</Card></div></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[Stethoscope,'专业医生','审核资质后提供线上咨询'],[Building2,'合作医院','承接检查、诊断与线下治疗'],[ShoppingBag,'品牌与营养','只推荐真实上架且适配的产品'],[FileText,'保险协同','经授权提供结构化病历，不替保险决策']].map(([Icon,title,text])=><Card key={String(title)} className="p-4"><Icon className="text-[#287656]" size={19}/><b className="mt-3 block text-sm">{String(title)}</b><p className="mt-1 text-xs leading-5 text-[#728078]">{String(text)}</p></Card>)}</div>
 {records.length>0&&<Card className="p-5"><SectionTitle>已保存需求</SectionTitle><div className="divide-y">{records.slice(0,10).map(x=><div key={x.id} className="py-3"><div className="flex justify-between gap-3"><b className="text-sm">{x.need}</b><Pill tone="amber">{x.status}</Pill></div><p className="mt-1 text-xs text-[#74827a]">{new Date(x.createdAt).toLocaleString('zh-CN',{hour12:false})} · {x.hospital||'未绑定医院'}</p><p className="mt-2 text-sm leading-6 text-[#5f7067]">{x.description}</p></div>)}</div></Card>}
 <Card className="border-[#e6c7c1] bg-[#fff5f3] p-4 text-sm leading-6 text-[#8a4b45]"><AlertTriangle className="mr-2 inline" size={18}/><b>紧急情况不等待线上回复：</b>呼吸困难、抽搐、无法站立、无尿/排尿困难、持续大量出血或意识异常，应立即前往就近有急诊能力的动物医院。</Card></div>;
}

function buildHandoff(profile:ReturnType<typeof usePetProfile>['profile']){
 const checkins=loadDailyCheckins(profile.id).slice(0,7);const symptoms=loadSymptomLogs(profile.id).slice(0,8);let reports:{createdAt?:string;reportTypeLabel?:string;sourceFile?:string}[]=[];try{reports=JSON.parse(localStorage.getItem(`petcare-medical-reports:${profile.id}`)||'[]').slice(0,5)}catch{reports=[]}
 return [`宠馨智 · 医疗协同资料包`,`生成时间：${new Date().toLocaleString('zh-CN',{hour12:false})}`,`数据范围：仅当前设备中由用户保存或上传的资料`,``,`一、宠物档案`,`姓名：${profile.name}；种类：${profile.species==='cat'?'猫':'犬'}；品种：${profile.breed}`,`年龄：${profile.age}；体重：${profile.weight||'未填'}kg；BCS：${profile.bcs||'未填'}/9`,`已记录疾病：${profile.disease||'未填'}；分期：${profile.stage||'未填'}`,`医院：${profile.hospital||'未填写'}；医生：${profile.doctor||'未填写'}`,``,`二、近7次健康打卡`,...(checkins.length?checkins.map(x=>`${new Date(x.recordedAt).toLocaleString('zh-CN',{hour12:false})}｜体重${x.weightKg??'未填'}kg｜饮水${x.waterMl??'未填'}ml｜食欲${x.appetite}｜精神${x.spirit}｜排尿${x.urine}`):['暂无健康打卡']),``,`三、近期症状`,...(symptoms.length?symptoms.map(x=>`${new Date(x.occurredAt).toLocaleString('zh-CN',{hour12:false})}｜${x.title}｜${x.description||'无详细描述'}`):['暂无症状记录']),``,`四、近期报告`,...(reports.length?reports.map(x=>`${x.createdAt?new Date(x.createdAt).toLocaleDateString('zh-CN'):'日期未填'}｜${x.reportTypeLabel||'未分类'}｜${x.sourceFile||'文件名未填'}`):['暂无已保存报告']),``,`医生重点核对：诊断依据、当前处方、剂量与禁忌、是否需要急诊或复查。`,`说明：本资料包用于提高沟通效率，不是诊断书或处方。`].join('\n');
}
