'use client';
import { useEffect,useState } from 'react';
import { ArrowLeft,Bluetooth,Plus,Router,Trash2 } from 'lucide-react';
import { usePetProfile } from './pet-profile-context';
import { Card,PageTitle,SectionTitle } from './ui';

type DeviceType='智能喂食器'|'循环饮水器'|'智能猫砂盆'|'体重秤'|'健康项圈';
type Device={id:string;name:string;serial:string;type:DeviceType;method:'manual'|'bluetooth';createdAt:string;bluetoothId?:string};
const types:DeviceType[]=['智能喂食器','循环饮水器','智能猫砂盆','体重秤','健康项圈'];
export function DeviceWorkspace({back}:{back:()=>void}){
 const {profile}=usePetProfile();const key=`petcare-devices:${profile.id}`;const [devices,setDevices]=useState<Device[]>([]);const [name,setName]=useState('');const [serial,setSerial]=useState('');const [type,setType]=useState<DeviceType>('智能喂食器');const [notice,setNotice]=useState('');
 useEffect(()=>{try{setDevices(JSON.parse(localStorage.getItem(key)||'[]'))}catch{setDevices([])}},[key]);
 const persist=(next:Device[])=>{setDevices(next);localStorage.setItem(key,JSON.stringify(next))};
 const add=()=>{if(!name.trim()||!serial.trim()){setNotice('请填写设备名称和序列号。');return}persist([{id:`device-${Date.now()}`,name:name.trim(),serial:serial.trim(),type,method:'manual',createdAt:new Date().toISOString()},...devices]);setName('');setSerial('');setNotice('设备资料已保存，但尚未验证或同步数据。')};
 const pair=async()=>{const nav=navigator as Navigator&{bluetooth?:{requestDevice:(options:{acceptAllDevices:boolean;optionalServices:unknown[]})=>Promise<{id:string;name?:string}>}};if(!nav.bluetooth){setNotice('当前浏览器或 file:// 运行方式不支持 Web Bluetooth。请在支持该能力的 HTTPS 页面中使用。');return}try{const found=await nav.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[]});persist([{id:`device-${Date.now()}`,name:found.name||'蓝牙设备',serial:found.id,type,method:'bluetooth',bluetoothId:found.id,createdAt:new Date().toISOString()},...devices]);setNotice('蓝牙设备已由用户实际选择并保存。读取健康数据仍需要厂商通信协议。')}catch{setNotice('未完成配对，没有保存设备。')}};
 return <div className="space-y-5"><PageTitle title="智能硬件中心" subtitle={`管理与 ${profile.name} 关联的真实设备，不生成演示读数`} action={<button onClick={back} className="flex items-center gap-2 rounded-xl border border-[#d7e2dc] bg-white px-3 py-2 text-sm"><ArrowLeft size={16}/>返回档案</button>}/>
  <Card className="p-5"><SectionTitle>添加设备</SectionTitle><div className="grid gap-3 md:grid-cols-3"><select value={type} onChange={e=>setType(e.target.value as DeviceType)} className="rounded-xl border border-[#d5e0d9] bg-white px-3 py-3 text-sm">{types.map(x=><option key={x}>{x}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} placeholder="设备名称，例如：客厅饮水器" className="rounded-xl border border-[#d5e0d9] px-3 py-3 text-sm"/><input value={serial} onChange={e=>setSerial(e.target.value)} placeholder="设备序列号 / SN" className="rounded-xl border border-[#d5e0d9] px-3 py-3 text-sm"/></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={add} className="flex items-center gap-2 rounded-xl bg-[#287656] px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/>保存设备资料</button><button onClick={pair} className="flex items-center gap-2 rounded-xl border border-[#7aa890] bg-white px-4 py-3 text-sm font-semibold text-[#286d51]"><Bluetooth size={18}/>尝试蓝牙配对</button></div>{notice&&<p className="mt-3 rounded-lg bg-[#f4f7f5] p-3 text-xs leading-5 text-[#607168]">{notice}</p>}</Card>
  <Card className="p-5"><SectionTitle>已登记设备</SectionTitle>{devices.length?<div className="divide-y divide-[#e5ebe7]">{devices.map(x=><div key={x.id} className="flex items-center gap-3 py-4"><span className="grid size-10 place-items-center rounded-xl bg-[#e8f2ed] text-[#287052]">{x.method==='bluetooth'?<Bluetooth size={19}/>:<Router size={19}/>}</span><div className="min-w-0 flex-1"><b className="block truncate">{x.name}</b><p className="mt-1 text-xs text-[#74827a]">{x.type} · SN {x.serial}</p><span className={`mt-2 inline-block rounded-full px-2 py-1 text-[11px] font-semibold ${x.method==='bluetooth'?'bg-[#e2f2e8] text-[#246c50]':'bg-[#f0f1f0] text-[#68756e]'}`}>{x.method==='bluetooth'?'蓝牙已配对':'用户录入，未验证'}</span></div><button onClick={()=>persist(devices.filter(d=>d.id!==x.id))} title="删除设备" aria-label="删除设备" className="grid size-9 place-items-center rounded-lg text-[#9b4b45] hover:bg-[#fff0ed]"><Trash2 size={17}/></button></div>)}</div>:<p className="py-8 text-center text-sm text-[#7b8981]">尚未登记设备，不显示虚构的在线设备或健康读数。</p>}</Card>
  <Card className="border-[#e6d6b5] bg-[#fffaf0] p-4 text-sm leading-6 text-[#756347]"><b>接入边界：</b>Wi-Fi 云同步、饮水量、进食克数、猫砂盆排尿和项圈活动数据，需要设备厂商提供协议、API 和后端鉴权。当前可完成真实设备建档与浏览器蓝牙选择，不会把“已登记”冒充“数据已同步”。</Card>
 </div>;
}
