'use client';

import { useEffect, useState } from 'react';
import {
  AlertTriangle, BarChart3, Bot, Building2, CalendarClock, CheckCircle2, ChevronRight, ClipboardPlus, FileCheck2,
  FolderHeart, LayoutDashboard, LogIn, PawPrint, Plus, RefreshCw, Search, ShieldCheck, Sparkles,
  Stethoscope, TicketCheck, Trash2, Users,
} from 'lucide-react';
import { getSupabaseClient, isSupabaseConfigured } from '@/lib/supabase-client';
import { loadCareAlerts } from '@/lib/care-coordination';
import { HospitalGrowthWorkspace } from './hospital-growth-workspace';
import { DoctorAlertWorkspace,DoctorFollowupWorkspace,DoctorOrdersWorkspace } from './doctor-care-coordination';

type HospitalPet={id:string;name:string;species:string;breed:string;disease:string;stage:string;weight_kg:number;owner?:string;avatar?:string;risk:'高'|'中'|'稳定';lastFollowup:string};
type PilotLead={id:string;hospital:string;contact:string;stage:'待联系'|'需求沟通'|'试用准备'|'试用中'|'待复盘'|'已合作';nextAction:string;updatedAt:string};
type DoctorView='workbench'|'alerts'|'cases'|'orders'|'followups'|'hospital';

const PILOT_KEY='petcare-hospital-pilot-leads';
const demoPets:HospitalPet[]=[
 {id:'demo-1',name:'团仔（演示）',species:'猫',breed:'英国短毛猫',disease:'CKD',stage:'IRIS 2期',weight_kg:5.2,owner:'演示宠主',risk:'高',lastFollowup:'演示时间'},
 {id:'demo-2',name:'布丁（演示）',species:'犬',breed:'混种犬',disease:'糖尿病',stage:'持续管理',weight_kg:12.8,owner:'演示宠主',risk:'中',lastFollowup:'演示时间'},
];
const navigation=[
 {id:'workbench' as const,label:'工作台',Icon:LayoutDashboard},
 {id:'alerts' as const,label:'待处理',Icon:AlertTriangle},
 {id:'cases' as const,label:'病例',Icon:FolderHeart},
 {id:'orders' as const,label:'医嘱',Icon:ClipboardPlus},
 {id:'followups' as const,label:'随访',Icon:CalendarClock},
 {id:'hospital' as const,label:'院方',Icon:Building2},
];

export function HospitalWorkspace(){
 const configured=isSupabaseConfigured();
 const [session,setSession]=useState(false);const [loading,setLoading]=useState(false);const [pets,setPets]=useState<HospitalPet[]>([]);const [demoMode,setDemoMode]=useState(false);const [query,setQuery]=useState('');const [form,setForm]=useState({email:'',password:''});const [error,setError]=useState('');const [view,setView]=useState<DoctorView>('workbench');
 const [localAlerts,setLocalAlerts]=useState<ReturnType<typeof loadCareAlerts>>([]);
 const [leads,setLeads]=useState<PilotLead[]>([]);const [lead,setLead]=useState({hospital:'',contact:'',stage:'待联系' as PilotLead['stage'],nextAction:''});
 useEffect(()=>{const target=new URLSearchParams(window.location.search).get('view');if(navigation.some(item=>item.id===target))setView(target as DoctorView)},[]);
 const loadPets=async()=>{const supabase=getSupabaseClient();if(!supabase)return;setLoading(true);const{data,error:loadError}=await supabase.from('pets').select('id,name,species,breed,disease,stage,weight_kg,updated_at').limit(100);if(loadError)setError(loadError.message);else setPets((data||[]).map((item)=>({...item,species:item.species==='cat'?'猫':'犬',owner:'已授权客户',risk:'稳定',lastFollowup:new Date(item.updated_at).toLocaleString('zh-CN')} as HospitalPet)));setLoading(false)};
 useEffect(()=>{try{setLeads(JSON.parse(localStorage.getItem(PILOT_KEY)||'[]'))}catch{setLeads([])}const alerts=loadCareAlerts();setLocalAlerts(alerts);const supabase=getSupabaseClient();if(!supabase){try{const local=JSON.parse(localStorage.getItem('petcare-pet-profiles-v3')||'[]') as {id:string;name:string;species:string;breed:string;disease:string;stage:string;weight:number;avatar?:string}[];setPets(local.map(item=>({id:item.id,name:item.name,species:item.species==='cat'?'猫':'犬',breed:item.breed,disease:item.disease,stage:item.stage,weight_kg:item.weight,avatar:item.avatar,owner:'本机宠主档案',risk:alerts.some(x=>x.petId===item.id&&x.status==='pending'&&x.level==='red')?'高':alerts.some(x=>x.petId===item.id&&x.status==='pending'&&['orange','yellow'].includes(x.level))?'中':'稳定',lastFollowup:'读取本机协同记录'})));}catch{setPets([])}return}supabase.auth.getSession().then(({data})=>{setSession(Boolean(data.session));if(data.session)void loadPets()});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>setSession(Boolean(next)));return()=>subscription.unsubscribe()},[]);
 const saveLeads=(next:PilotLead[])=>{setLeads(next);localStorage.setItem(PILOT_KEY,JSON.stringify(next))};
 const addLead=()=>{if(!lead.hospital.trim()||!lead.nextAction.trim())return;saveLeads([{id:`pilot-${Date.now()}`,hospital:lead.hospital.trim(),contact:lead.contact.trim(),stage:lead.stage,nextAction:lead.nextAction.trim(),updatedAt:new Date().toISOString()},...leads]);setLead({hospital:'',contact:'',stage:'待联系',nextAction:''})};
 const updateLead=(id:string,stage:PilotLead['stage'])=>saveLeads(leads.map(item=>item.id===id?{...item,stage,updatedAt:new Date().toISOString()}:item));
 const login=async()=>{const supabase=getSupabaseClient();if(!supabase)return;setLoading(true);setError('');const{error:loginError}=await supabase.auth.signInWithPassword(form);if(loginError)setError(loginError.message);else{setSession(true);await loadPets()}setLoading(false)};
 if(configured&&!session)return <DoctorLogin form={form} setForm={setForm} error={error} loading={loading} login={login}/>;
 const shown=pets.filter(item=>`${item.name}${item.owner}${item.disease}${item.stage}`.toLowerCase().includes(query.toLowerCase()));
 const pendingAlerts=localAlerts.filter(item=>item.status==='pending');
 const counts={cases:pets.length,alerts:pendingAlerts.length,red:pendingAlerts.filter(item=>item.level==='red').length,attention:pendingAlerts.filter(item=>item.level==='orange'||item.level==='yellow').length,reports:0,tickets:0};
 return <div className="doctor-app mx-auto min-h-screen max-w-[430px] bg-[#f2f8fb] pb-24 text-[#173044] shadow-[0_0_45px_rgba(28,68,91,.11)]">
  <header className="sticky top-0 z-40 border-b border-[#dbe7eb] bg-white/96 backdrop-blur-xl"><div className="mx-auto flex min-h-16 w-full max-w-[430px] items-center justify-between gap-3 px-4"><button onClick={()=>setView('workbench')} className="flex items-center gap-3 text-left"><span className="grid size-10 place-items-center rounded-[14px] bg-[#3678a3] text-white shadow-sm"><Stethoscope size={21}/></span><span><b className="block text-[#215779]">宠馨智</b><small className="text-[#6e808b]">让专业的关怀延续</small></span></button><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1.5 text-[10px] font-semibold ${configured?'bg-green-100 text-green-800':demoMode?'bg-red-100 text-red-800':'bg-amber-100 text-amber-800'}`}>{configured?'在线接诊':demoMode?'演示数据':'本机预览'}</span><a href="portal.html" className="grid size-9 place-items-center rounded-xl border text-[10px]">总览</a></div></div></header>
  <main className="mx-auto w-full max-w-[430px] px-3 py-3">
   {view==='workbench'&&<DoctorWorkbench counts={counts} pets={shown} configured={configured} demoMode={demoMode} setDemoMode={setDemoMode} setPets={setPets} setView={setView}/>} 
   {view==='alerts'&&<DoctorAlertWorkspace/>}
   {view==='cases'&&<CaseQueue shown={shown} query={query} setQuery={setQuery} loadPets={loadPets} loading={loading} configured={configured} demoMode={demoMode}/>} 
   {view==='orders'&&<DoctorOrdersWorkspace/>} 
   {view==='followups'&&<DoctorFollowupWorkspace/>} 
   {view==='hospital'&&<HospitalOperations leads={leads} lead={lead} setLead={setLead} addLead={addLead} updateLead={updateLead} saveLeads={saveLeads}/>} 
  </main>
  <nav className="fixed bottom-0 left-1/2 z-50 grid w-full max-w-[430px] -translate-x-1/2 grid-cols-6 border-x border-t border-[#dbe7eb] bg-white/96 px-1 pb-[max(.45rem,env(safe-area-inset-bottom))] pt-2 shadow-[0_-8px_24px_rgba(23,67,75,.10)] backdrop-blur-xl">{navigation.map(({id,label,Icon})=><button key={id} onClick={()=>setView(id)} className={`flex flex-col items-center gap-1 py-1 text-[9px] ${view===id?'font-semibold text-[#2e7099]':'text-[#758891]'}`}><span className={`grid size-8 place-items-center rounded-xl ${view===id?'bg-[#e6f1f8]':''}`}><Icon size={19} strokeWidth={view===id?2.5:2}/></span>{label}</button>)}</nav>
 </div>;
}

function DoctorLogin({form,setForm,error,loading,login}:{form:{email:string;password:string};setForm:(value:{email:string;password:string})=>void;error:string;loading:boolean;login:()=>void}){
 return <div className="grid min-h-screen place-items-center bg-[linear-gradient(145deg,#edf7f6,#f2f6fa)] p-5"><div className="w-full max-w-md rounded-[28px] border border-[#d9e7e8] bg-white p-7 shadow-[0_22px_60px_rgba(26,72,78,.10)]"><span className="grid size-12 place-items-center rounded-2xl bg-[#e4f2f2] text-[#176b70]"><Stethoscope/></span><h1 className="mt-5 text-2xl font-bold">医生工作台登录</h1><p className="mt-2 text-sm leading-6 text-[#71828a]">仅限已获授权且完成医院绑定的执业医生使用。</p><input value={form.email} onChange={event=>setForm({...form,email:event.target.value})} placeholder="工作邮箱" className="mt-5 w-full rounded-xl border border-[#d9e3e6] px-4 py-3 outline-none focus:border-[#347c80]"/><input type="password" value={form.password} onChange={event=>setForm({...form,password:event.target.value})} placeholder="密码" className="mt-3 w-full rounded-xl border border-[#d9e3e6] px-4 py-3 outline-none focus:border-[#347c80]"/>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<button onClick={login} disabled={loading||!form.email||!form.password} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#176b70] py-3 font-semibold text-white disabled:bg-gray-400"><LogIn size={18}/>{loading?'正在验证…':'登录医生端'}</button></div></div>;
}

function DoctorWorkbench({counts,pets,configured,demoMode,setDemoMode,setPets,setView}:{counts:{cases:number;alerts:number;red:number;attention:number;reports:number;tickets:number};pets:HospitalPet[];configured:boolean;demoMode:boolean;setDemoMode:(value:boolean)=>void;setPets:(value:HospitalPet[])=>void;setView:(view:DoctorView)=>void}){
 return <div className="space-y-3">
  <section className="doctor-hero"><div><p>院后护理 · 今日工作</p><h1>上午好，医生</h1><span>{configured?'已连接医院账号，可处理授权病例':'本机协同预览 · 先处理风险，再进入病例'}</span></div><div className="doctor-hero-mark"><Stethoscope size={28}/><small>专业 · 同行</small></div></section>
  {!configured?<section className="doctor-preview-strip"><span><b>本机预览</b> 读取同一浏览器中宠主保存的档案和提醒</span><button onClick={()=>{setDemoMode(!demoMode);setPets(demoMode?[]:demoPets)}}>{demoMode?'退出演示':'查看演示'}</button></section>:null}
  {demoMode?<div className="rounded-xl border border-red-300 bg-red-50 px-3 py-2 text-[11px] font-bold text-red-800">当前病例均标记为演示数据，不代表真实医院或真实宠物。</div>:null}

  <section className="doctor-risk-summary"><div className="doctor-section-head"><div><h2>今天先处理</h2><p>只展示风险数量，点击后进入完整队列</p></div><button onClick={()=>setView('alerts')}>进入待处理 ›</button></div><div className="grid grid-cols-3 gap-2"><PriorityButton icon={AlertTriangle} title="需要关注" detail="立即处理" value={counts.red} tone="red" onClick={()=>setView('alerts')}/><PriorityButton icon={CalendarClock} title="等待处理" detail="趋势或漏执行" value={counts.attention} tone="amber" onClick={()=>setView('alerts')}/><PriorityButton icon={CheckCircle2} title="状态稳定" detail="无需处理" value={Math.max(0,counts.cases-counts.alerts)} tone="green" onClick={()=>setView('cases')}/></div></section>

  <section className="doctor-directory"><div className="doctor-section-head"><div><h2>工作目录</h2><p>选择工作类型后，再查看对应病例和操作表单</p></div></div><div className="doctor-directory-grid">
   <button onClick={()=>setView('alerts')} className="red"><span><AlertTriangle size={19}/></span><span><b>异常待处理</b><small>红黄风险与漏执行</small></span><ChevronRight size={15}/></button>
   <button onClick={()=>setView('cases')} className="blue"><span><FolderHeart size={19}/></span><span><b>授权病例</b><small>{counts.cases}个本院授权病例</small></span><ChevronRight size={15}/></button>
   <button onClick={()=>setView('orders')} className="green"><span><ClipboardPlus size={19}/></span><span><b>护理方案</b><small>制定、审核和发布</small></span><ChevronRight size={15}/></button>
   <button onClick={()=>setView('followups')} className="cyan"><span><BarChart3 size={19}/></span><span><b>执行趋势</b><small>打卡、变化与随访</small></span><ChevronRight size={15}/></button>
   <button onClick={()=>setView('followups')} className="purple"><span><FileCheck2 size={19}/></span><span><b>复诊效果</b><small>对比检查与护理结果</small></span><ChevronRight size={15}/></button>
   <button onClick={()=>setView('hospital')} className="amber"><span><Building2 size={19}/></span><span><b>院方管理</b><small>资质、服务与合作试点</small></span><ChevronRight size={15}/></button>
  </div></section>

  <button onClick={()=>setView('orders')} className="doctor-ai-strip"><span className="grid size-10 place-items-center rounded-xl bg-[#e7f1ff] text-[#3877a1]"><Bot size={21}/></span><span className="min-w-0 flex-1 text-left"><b>AI管家助手</b><small>根据医生医嘱拆任务、整理趋势和风险；不诊断、不改药</small></span><span className="font-bold text-[#39779e]">进入 ›</span></button>
 </div>;
}

function PriorityButton({icon:Icon,title,detail,value,tone,onClick}:{icon:typeof AlertTriangle;title:string;detail:string;value:number;tone:'red'|'amber'|'green';onClick:()=>void}){const tones={red:'border-[#f0c3bf] bg-[#fff3f1] text-[#a84d45]',amber:'border-[#edd8b2] bg-[#fff8eb] text-[#9a6820]',green:'border-[#cae2d6] bg-[#eff9f4] text-[#287354]'};return <button onClick={onClick} className={`flex min-h-28 flex-col items-start justify-between rounded-2xl border p-3 text-left ${tones[tone]}`}><span className="flex w-full items-start justify-between"><Icon size={19}/><strong className="text-2xl">{value}</strong></span><span><b className="block text-xs text-[#263d49]">{title}</b><small className="mt-1 block text-[9px] text-[#70818a]">{detail}</small></span></button>}
function SmallMetric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:number}){return <div className="rounded-xl bg-[#f5f8f8] p-3"><Icon size={17} className="text-[#267176]"/><p className="mt-2 text-xs text-[#73838a]">{label}</p><b className="mt-1 block text-xl">{value}</b></div>}

function CaseQueue({shown,query,setQuery,loadPets,loading,configured,demoMode}:{shown:HospitalPet[];query:string;setQuery:(value:string)=>void;loadPets:()=>Promise<void>;loading:boolean;configured:boolean;demoMode:boolean}){
 return <><PageHeading title="授权病例" description="从宠物和病情进入，不在首页堆放全部功能。"/><section className="rounded-2xl border border-[#dbe6e8] bg-white"><div className="flex flex-col justify-between gap-3 border-b border-[#e3ebed] p-4 sm:flex-row sm:items-center"><div><h2 className="font-bold">慢性病客户工作队列</h2><p className="mt-1 text-xs text-[#778992]">正式版本仅显示宠主授权给本医院的数据</p></div><div className="flex gap-2"><label className="flex flex-1 items-center gap-2 rounded-xl border border-[#d8e4e6] px-3"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索宠物/病种" className="min-w-0 flex-1 py-2.5 text-sm outline-none"/></label><button onClick={()=>void loadPets()} disabled={!configured} title={!configured?'尚未连接后台':'刷新'} className="grid size-10 place-items-center rounded-xl border disabled:opacity-40"><RefreshCw size={16} className={loading?'animate-spin':''}/></button></div></div>{shown.length===0?<div className="p-12 text-center text-sm text-[#71838c]"><FolderHeart className="mx-auto mb-3 text-[#8ba0a8]"/><b className="block text-base text-[#405761]">暂无病例数据</b><span className="mt-2 block">先在宠主端建档，或连接后台并取得授权。</span></div>:<div className="divide-y divide-[#e5ecee]">{shown.map(item=><article key={item.id} className="grid gap-3 p-4 sm:grid-cols-[1.3fr_1fr_.55fr_.8fr_1fr] sm:items-center"><div><b>{item.name}</b><p className="mt-1 text-xs text-[#778992]">{item.species} · {item.breed} · {item.owner}</p></div><div className="text-sm">{item.disease}<small className="mt-1 block text-[#778992]">{item.stage}</small></div><span className="text-sm">{item.weight_kg}kg</span><span className={`w-fit rounded-full px-2 py-1 text-xs font-semibold ${item.risk==='高'?'bg-red-100 text-red-700':item.risk==='中'?'bg-amber-100 text-amber-800':'bg-green-100 text-green-700'}`}>{item.risk==='高'?'红色·紧急':item.risk==='中'?'黄色·待复核':'绿色·稳定'}</span><div className="text-xs text-[#687c85]">{item.lastFollowup}<span className={`mt-1 block font-semibold ${demoMode?'text-red-700':configured?'text-green-700':'text-amber-700'}`}>{demoMode?'演示数据':configured?'医院授权同步':'本机协同预览'}</span></div></article>)}</div>}</section></>;
}

function OrdersWorkspace({counts}:{counts:{cases:number;alerts:number;reports:number;tickets:number}}){return <><PageHeading title="医嘱与护理方案" description="医生负责诊疗决定，AI负责把已确认医嘱变成可执行的院后任务。"/><div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-[#cfe2dc] bg-white p-5"><div className="flex items-start gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-[#e7f5ef] text-[#267256]"><ClipboardPlus/></span><div><h2 className="font-bold">医生下达方案</h2><p className="mt-1 text-sm leading-6 text-[#687b74]">选择授权病例，填写诊断后的医嘱，再由AI拆成用药、饮食、饮水、监测和活动任务草稿。</p></div></div><ol className="mt-5 grid gap-3 sm:grid-cols-3">{['1. 选择病例','2. 填写并确认医嘱','3. 审核任务后发布'].map(item=><li key={item} className="rounded-xl bg-[#f2f7f5] p-3 text-sm font-semibold text-[#456558]">{item}</li>)}</ol><div className="mt-5 rounded-xl border border-dashed border-[#bdcec8] p-5 text-sm leading-6 text-[#667970]">生产版本操作入口已放在统一微信小程序的医生角色页面；当前网页只负责完整展示流程，不伪造未连接后台的病例和医嘱。</div></section><section className="space-y-3"><RoleBlock icon={Stethoscope} title="执业医生" detail="诊断与治疗决策、签署护理方案、处理异常。"/><RoleBlock icon={Sparkles} title="AI文书助手" detail="拆解已签署方案、汇总家庭指标；不诊断、不改药。"/><RoleBlock icon={ShieldCheck} title="发布边界" detail={`当前有${counts.cases}个病例；所有AI任务必须经医生确认才对宠主可见。`}/></section></div></>}

function FollowupWorkspace({pets,setView}:{pets:HospitalPet[];setView:(view:DoctorView)=>void}){return <><PageHeading title="执行复核与随访" description="先看趋势和漏执行，再决定是否联系宠主或安排复诊。"/><section className="rounded-2xl border border-[#dbe6e8] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">随访队列</h2><p className="mt-1 text-xs text-[#758790]">真实提醒需要统一API、通知服务和医生账号连接</p></div><CalendarClock className="text-[#34759c]"/></div>{pets.length?<div className="mt-4 divide-y divide-[#e5ecee]">{pets.map(item=><div key={item.id} className="flex items-center gap-3 py-4"><span className="grid size-10 place-items-center rounded-xl bg-[#edf5fa] text-[#34759c]"><FolderHeart size={18}/></span><span className="min-w-0 flex-1"><b>{item.name} · {item.disease}</b><small className="mt-1 block text-[#74868e]">最近随访：{item.lastFollowup}</small></span><span className="text-xs text-[#6f828a]">{item.stage}</span></div>)}</div>:<div className="mt-5 rounded-xl border border-dashed p-8 text-center text-sm text-[#758790]">暂无已授权的随访病例。</div>}<button onClick={()=>setView('cases')} className="mt-5 rounded-xl bg-[#176b70] px-4 py-2.5 text-sm font-semibold text-white">进入病例核对原始记录</button></section></>}

function HospitalOperations({leads,lead,setLead,addLead,updateLead,saveLeads}:{leads:PilotLead[];lead:{hospital:string;contact:string;stage:PilotLead['stage'];nextAction:string};setLead:(value:{hospital:string;contact:string;stage:PilotLead['stage'];nextAction:string})=>void;addLead:()=>void;updateLead:(id:string,stage:PilotLead['stage'])=>void;saveLeads:(value:PilotLead[])=>void}){return <><PageHeading title="院方资料与运营" description="资质、公开特色、急诊值班、地区曝光和合作试点统一归到院方模块。"/><section className="mb-5 rounded-2xl border border-[#dbe6e8] bg-white p-5"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-[#287656]"/><div><h2 className="font-bold">合作试点启动台</h2><p className="mt-1 text-sm leading-6 text-[#667970]">只保存你自己录入的合作线索，不自动抓取医院名单。</p></div></div><div className="mt-4 grid gap-2 md:grid-cols-4">{['1. 医院需求沟通','2. 宠主明确授权','3. 真实病例试用','4. 复诊与依从性复盘'].map(item=><div key={item} className="rounded-xl bg-[#f2f7f5] p-3 text-xs font-semibold text-[#3f6653]">{item}</div>)}</div><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_1fr_160px_1.4fr_auto]"><input value={lead.hospital} onChange={event=>setLead({...lead,hospital:event.target.value})} placeholder="真实医院名称" className="rounded-xl border px-3 py-2.5 text-sm"/><input value={lead.contact} onChange={event=>setLead({...lead,contact:event.target.value})} placeholder="联系人/联系方式（选填）" className="rounded-xl border px-3 py-2.5 text-sm"/><select value={lead.stage} onChange={event=>setLead({...lead,stage:event.target.value as PilotLead['stage']})} className="rounded-xl border bg-white px-3 py-2.5 text-sm">{['待联系','需求沟通','试用准备','试用中','待复盘','已合作'].map(item=><option key={item}>{item}</option>)}</select><input value={lead.nextAction} onChange={event=>setLead({...lead,nextAction:event.target.value})} placeholder="下一步，例如：约院长演示真实病例流程" className="rounded-xl border px-3 py-2.5 text-sm"/><button onClick={addLead} disabled={!lead.hospital.trim()||!lead.nextAction.trim()} className="flex items-center justify-center gap-2 rounded-xl bg-[#287656] px-4 py-2.5 text-sm font-semibold text-white disabled:bg-gray-300"><Plus size={16}/>保存</button></div>{leads.length?<div className="mt-4 divide-y rounded-xl border">{leads.map(item=><div key={item.id} className="grid gap-2 p-3 text-sm sm:grid-cols-[1fr_1fr_150px_1.4fr_auto] sm:items-center"><b>{item.hospital}</b><span>{item.contact||'未填'}</span><select value={item.stage} onChange={event=>updateLead(item.id,event.target.value as PilotLead['stage'])} className="rounded-md border bg-white px-2 py-1.5 text-xs">{['待联系','需求沟通','试用准备','试用中','待复盘','已合作'].map(stage=><option key={stage}>{stage}</option>)}</select><span>{item.nextAction}</span><button onClick={()=>saveLeads(leads.filter(value=>value.id!==item.id))} title="删除线索" className="text-[#9b4a44]"><Trash2 size={16}/></button></div>)}</div>:<p className="mt-4 rounded-xl border border-dashed p-4 text-center text-sm text-[#7b8981]">尚未录入合作医院。</p>}</section><HospitalGrowthWorkspace/></>}

function RoleBlock({icon:Icon,title,detail}:{icon:typeof Stethoscope;title:string;detail:string}){return <div className="flex items-start gap-3 rounded-2xl border border-[#dbe6e8] bg-white p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#edf5f5] text-[#176b70]"><Icon size={19}/></span><div><b>{title}</b><p className="mt-1 text-sm leading-6 text-[#687b84]">{detail}</p></div></div>}
function PageHeading({title,description}:{title:string;description:string}){return <div className="mb-5"><h1 className="text-2xl font-bold sm:text-3xl">{title}</h1><p className="mt-2 text-sm leading-6 text-[#687c85]">{description}</p></div>}
