'use client';
import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle,Boxes,ChevronRight,PackagePlus,Settings2,ShoppingBag,Warehouse } from 'lucide-react';
import { usePetProfile } from './pet-profile-context';
import { Card,PageTitle,Pill,SectionTitle } from './ui';

type ProductStatus='planning'|'published'|'paused';
type Product={id:string;name:string;category:string;species:'猫'|'犬'|'猫犬';diseases:string[];description:string;price:string;stock:string;purchaseUrl:string;status:ProductStatus;regulated?:boolean};
const KEY='petcare-owner-product-catalog-v1';
const opportunities:Product[]=[
 ['renal-food','肾脏处方营养干粮/湿粮','处方营养','猫犬',['CKD','肾病'],'低磷、适量优质蛋白的分期营养产品线','','','', 'planning'],
 ['renal-support','肾脏营养支持品','营养补充','猫犬',['CKD','肾病'],'Omega-3、益生菌等产品需有完整成分与质检依据','','','', 'planning'],
 ['phosphate','磷结合剂处方配送','处方药品','猫犬',['CKD','肾病','高磷'],'必须凭兽医处方并具备药品经营及配送资质','','','', 'planning',true],
 ['diabetes-food','糖尿病专用营养粮','处方营养','猫犬',['糖尿病'],'按兽医营养目标设计的控糖产品线','','','', 'planning'],
 ['glucose','血糖监测耗材','监测耗材','猫犬',['糖尿病'],'宠物血糖仪、试纸、采血耗材与记录配套','','','', 'planning'],
 ['pancreas','低脂胰腺护理粮','处方营养','犬',['胰腺炎','高脂血症'],'低脂、易消化产品线，具体适用由兽医确认','','','', 'planning'],
 ['hepatic','肝脏护理营养粮','处方营养','猫犬',['肝病','肝功能'],'按病因和阶段区分，不与肾病粮混用','','','', 'planning'],
 ['urinary','泌尿道处方营养产品','处方营养','猫犬',['泌尿','结石'],'按结石类型和尿液目标区分产品','','','', 'planning'],
 ['gastro','肠胃护理营养产品','处方营养','猫犬',['肠胃','腹泻','IBD'],'易消化、低脂或高纤维产品需分开设计','','','', 'planning'],
 ['cardiac','心脏护理营养产品','处方营养','猫犬',['心脏病','心衰'],'钠和营养目标须结合兽医诊断','','','', 'planning'],
 ['derma','皮肤过敏护理产品','处方营养','猫犬',['皮肤','过敏'],'水解蛋白、单一蛋白和皮肤屏障产品线','','','', 'planning'],
 ['joint','关节与活动支持产品','营养补充','猫犬',['关节','骨科'],'体重管理与关节支持组合','','','', 'planning'],
 ['weight','体重管理营养产品','处方营养','猫犬',['肥胖','超重'],'根据实测体重和BCS制定能量目标','','','', 'planning'],
 ['recovery','术后与康复营养产品','处方营养','猫犬',['术后','康复','消瘦'],'高能量、适口性产品，需排除禁忌','','','', 'planning'],
 ['feeder','智能热量喂食器','智能硬件','猫犬',['糖尿病','肥胖','CKD'],'称重出粮、餐次记录和异常提醒','','','', 'planning'],
 ['fountain','过滤循环智能饮水器','智能硬件','猫犬',['CKD','泌尿','糖尿病'],'过滤耗材、水量记录和清洁提醒','','','', 'planning'],
 ['litter','智能猫砂盆与专用猫砂','智能硬件','猫',['CKD','泌尿','糖尿病'],'体重、如厕频率和尿团变化趋势记录','','','', 'planning'],
 ['collar','健康项圈与智能体重秤','智能硬件','猫犬',['慢性病'],'活动、休息与连续体重趋势采集','','','', 'planning'],
].map(x=>({id:x[0] as string,name:x[1] as string,category:x[2] as string,species:x[3] as Product['species'],diseases:x[4] as string[],description:x[5] as string,price:x[6] as string,stock:x[7] as string,purchaseUrl:x[8] as string,status:x[9] as ProductStatus,regulated:Boolean(x[10])}));

export function MarketplacePage(){
 const {profile}=usePetProfile();const [mode,setMode]=useState<'store'|'developer'>('store');const [items,setItems]=useState<Product[]>([]);const [selected,setSelected]=useState<Product|null>(null);const [notice,setNotice]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||'[]') as Product[];setItems(saved.length?[...opportunities.map(o=>saved.find(x=>x.id===o.id)||o),...saved.filter(x=>!opportunities.some(o=>o.id===x.id))]:opportunities)}catch{setItems(opportunities)}},[]);
 const persist=(next:Product[])=>{setItems(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const published=items.filter(x=>x.status==='published');const recommended=useMemo(()=>published.filter(x=>(x.species==='猫犬'||x.species===(profile.species==='cat'?'猫':'犬'))&&x.diseases.some(d=>(profile.disease||'').toLowerCase().includes(d.toLowerCase())||d.toLowerCase().includes((profile.disease||'').toLowerCase()))),[published,profile]);
 const save=(product:Product,publish=false)=>{if(publish&&(product.regulated||!product.name.trim()||!Number(product.price)||!Number(product.stock)||!/^https?:\/\//.test(product.purchaseUrl))){setNotice(product.regulated?'药品类不能在当前未接入资质与处方审核的版本发布。':'发布前必须填写商品名、有效价格、库存和以 http/https 开头的真实购买链接。');return}const next=items.map(x=>x.id===product.id?{...product,status:publish?'published':product.status}:x);persist(next);setSelected(null);setNotice(publish?'商品已发布，用户商城现在可以看到。':'商品资料已保存。')};
 return <div className="space-y-5"><PageTitle title="宠馨智自有品牌商城" subtitle="开发者管理真实商品，宠物主人按当前宠物资料选购" action={<div className="flex rounded-xl bg-[#e5ece8] p-1"><button onClick={()=>setMode('store')} className={`rounded-lg px-3 py-2 text-sm ${mode==='store'?'bg-white font-semibold text-[#246b4e] shadow-sm':'text-[#68776f]'}`}>用户商城</button><button onClick={()=>setMode('developer')} className={`rounded-lg px-3 py-2 text-sm ${mode==='developer'?'bg-white font-semibold text-[#246b4e] shadow-sm':'text-[#68776f]'}`}>开发者管理</button></div>}/>
  {mode==='store'?<><Card className="border-[#d4e4da] bg-[#f5faf7] p-4 text-sm leading-6 text-[#52675b]"><b>个体化展示依据：</b>{profile.name} · {profile.species==='cat'?'猫':'犬'} · 已填写病种“{profile.disease||'未填写'}”。商品只是营养和护理工具，不能替代兽医诊断、处方、补液或用药方案。</Card>{recommended.length>0&&<section><SectionTitle>更符合当前档案</SectionTitle><ProductGrid products={recommended}/></section>}<section><SectionTitle>全部已上架商品 <span className="text-xs font-normal text-[#78867e]">{published.length} 件</span></SectionTitle>{published.length?<ProductGrid products={published}/>:<Card className="p-10 text-center"><ShoppingBag className="mx-auto text-[#39795e]" size={34}/><b className="mt-4 block">暂时没有真实上架商品</b><p className="mt-2 text-sm text-[#718078]">开发者填写自有品牌商品、库存和购买链接并发布后，商品才会出现在这里。</p></Card>}</section></>:
  <><Card className="border-[#ead29f] bg-[#fff9ed] p-4 text-sm leading-6 text-[#725d35]"><b>开发者端说明：</b>以下是产品线规划清单，不代表已经生产、取得许可或有库存。发布后会进入用户商城；药品必须在取得经营资质、处方审核和合规配送能力后通过正式后台开放。</Card>{notice&&<p className="rounded-xl bg-[#edf5f0] p-3 text-sm font-semibold text-[#2b6d52]">{notice}</p>}{selected?<Editor product={selected} cancel={()=>setSelected(null)} save={save}/>:<><div className="grid gap-3 sm:grid-cols-3"><Metric icon={Boxes} label="规划品类" value={String(items.length)}/><Metric icon={Warehouse} label="已发布" value={String(published.length)}/><Metric icon={PackagePlus} label="待完善" value={String(items.filter(x=>x.status==='planning').length)}/></div><Card className="overflow-hidden"><div className="border-b border-[#e1e8e4] p-4"><SectionTitle>自有品牌产品线规划</SectionTitle></div><div className="divide-y divide-[#e5ebe7]">{items.map(x=><button key={x.id} onClick={()=>setSelected({...x})} className="flex w-full items-center gap-3 p-4 text-left hover:bg-[#f7faf8]"><span className="grid size-10 place-items-center rounded-xl bg-[#e7f2ec] text-[#287052]"><Settings2 size={18}/></span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{x.name}</b><small className="mt-1 block text-[#74827a]">{x.category} · {x.species} · {x.diseases.join(' / ')}</small></span>{x.regulated?<Pill tone="red">需经营资质</Pill>:<Pill tone={x.status==='published'?'green':'amber'}>{x.status==='published'?'已发布':'待开发'}</Pill>}<ChevronRight size={17}/></button>)}</div></Card></>}</>}
 </div>;
}
function ProductGrid({products}:{products:Product[]}){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{products.map(x=><Card key={x.id} className="p-5"><div className="flex items-center justify-between"><Pill>{x.category}</Pill><span className="text-xs text-[#77857d]">库存 {x.stock}</span></div><h2 className="mt-4 font-bold">{x.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-[#687870]">{x.description}</p><div className="mt-3 flex flex-wrap gap-1">{x.diseases.map(d=><span key={d} className="rounded bg-[#f0f4f2] px-2 py-1 text-[11px] text-[#687870]">{d}</span>)}</div><div className="mt-5 flex items-center justify-between"><b className="text-xl text-[#286d51]">¥{Number(x.price).toFixed(2)}</b><a href={x.purchaseUrl} target="_blank" rel="noreferrer" className="rounded-xl bg-[#287656] px-4 py-2.5 text-sm font-semibold text-white">立即购买</a></div></Card>)}</div>}
function Editor({product,cancel,save}:{product:Product;cancel:()=>void;save:(p:Product,publish?:boolean)=>void}){const [form,setForm]=useState(product);const input='mt-1 w-full rounded-xl border border-[#d5e0d9] px-3 py-2.5 text-sm';return <Card className="p-5"><SectionTitle>完善商品资料</SectionTitle>{form.regulated&&<div className="mb-4 flex gap-2 rounded-xl bg-[#fff0ed] p-3 text-sm leading-6 text-[#9b453d]"><AlertTriangle className="shrink-0" size={19}/>这是药品经营范围，当前静态版本禁止直接发布。正式上线必须接入资质审核、兽医处方、支付、订单和合规配送后台。</div>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">商品名称<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={input}/></label><label className="text-sm font-semibold">品牌/分类<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className={input}/></label><label className="text-sm font-semibold">售价（元）<input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} className={input}/></label><label className="text-sm font-semibold">可售库存<input type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})} className={input}/></label><label className="text-sm font-semibold sm:col-span-2">真实购买/收银台链接<input value={form.purchaseUrl} onChange={e=>setForm({...form,purchaseUrl:e.target.value})} placeholder="https://..." className={input}/></label><label className="text-sm font-semibold sm:col-span-2">商品说明<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} className={input}/></label></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>save(form)} className="rounded-xl border border-[#9abdab] px-4 py-2.5 text-sm font-semibold text-[#286d51]">保存草稿</button><button onClick={()=>save(form,true)} disabled={form.regulated} className="rounded-xl bg-[#287656] px-4 py-2.5 text-sm font-semibold text-white disabled:bg-[#adb9b2]">发布到用户商城</button><button onClick={cancel} className="px-4 py-2.5 text-sm text-[#6f7d75]">取消</button></div></Card>}
function Metric({icon:Icon,label,value}:{icon:typeof Boxes;label:string;value:string}){return <Card className="flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-[#e7f2ec] text-[#287052]"><Icon size={19}/></span><span><small className="text-[#74827a]">{label}</small><b className="block text-xl">{value}</b></span></Card>}
