'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Archive, Camera, ChevronDown, ClipboardPaste, FileScan, History, Library, LoaderCircle, ShieldCheck, Upload } from 'lucide-react';
import { analyzeReportText, createPendingOcrResult, type MedicalReportAnalysis } from '@/lib/medical-report-analyzer';
import { COZE_REPORT_SYSTEM_PROMPT, REPORT_CASE_LIBRARY, REPORT_DEMO_TEXT, REPORT_TEMPLATE_LIBRARY, REPORT_TYPES, type ReportType } from '@/lib/medical-report-knowledge';
import { usePetProfile } from './pet-profile-context';
import { Card, PageTitle, Pill, SectionTitle } from './ui';
import { CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';

const storageKey=(petId:string)=>`petcare-medical-reports:${petId}`;
const riskMeta={urgent:{label:'危急风险',classes:'border-[#e09a91] bg-[#fff0ed] text-[#9f3933]'},warning:{label:'需要警惕',classes:'border-[#e8c982] bg-[#fff8e7] text-[#8a5c16]'},attention:{label:'继续观察',classes:'border-[#bcd9c7] bg-[#eff8f2] text-[#286c4f]'}};

export function MedicalReportWorkspace({back}:{back:()=>void}){
  const {profile}=usePetProfile();
  const [type,setType]=useState<ReportType>('auto'); const [text,setText]=useState('');
  const [diagnosisStatus,setDiagnosisStatus]=useState<'undiagnosed'|'diagnosed'>('undiagnosed');
  const [symptoms,setSymptoms]=useState(''); const [previewUrl,setPreviewUrl]=useState('');
  const [result,setResult]=useState<MedicalReportAnalysis|null>(null); const [history,setHistory]=useState<MedicalReportAnalysis[]>([]);
  const [caseFilter,setCaseFilter]=useState<'all'|'猫'|'犬'>('all');
  const [trendMetric,setTrendMetric]=useState('');
  const [loading,setLoading]=useState(false); const [saved,setSaved]=useState(false); const inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem(storageKey(profile.id))||'[]'));}catch{setHistory([])}},[profile.id]);
  const withContext=(content:string)=>`${content}\n诊断状态：${diagnosisStatus==='diagnosed'?'已有兽医诊断':'尚未确诊'}\n当前症状：${symptoms||'未填写'}`;
  const analyze=(content=text,file='粘贴的报告文字')=>{if(!content.trim())return;setLoading(true);setSaved(false);window.setTimeout(()=>{setResult(analyzeReportText(withContext(content),file,type));setLoading(false)},350)};
  const upload=(file?:File)=>{if(!file)return;setSaved(false);if(previewUrl)URL.revokeObjectURL(previewUrl);if(file.type.startsWith('image/'))setPreviewUrl(URL.createObjectURL(file));setResult(createPendingOcrResult(file,type));};
  const save=()=>{if(!result)return;const next=[{...result,pet:{...result.pet,name:profile.name,species:profile.species}},...history.filter(x=>x.id!==result.id)].slice(0,30);setHistory(next);localStorage.setItem(storageKey(profile.id),JSON.stringify(next));setSaved(true)};
  const grouped=useMemo(()=>result?.dailyCarePlan||[],[result]);
  const metricNames=useMemo(()=>Array.from(new Set(history.flatMap(r=>[...r.abnormalItems,...(r.normalItems||[])].map(x=>x.name)))),[history]);
  const activeMetric=trendMetric||metricNames[0]||'';
  const trendData=useMemo(()=>history.map(r=>{const item=[...r.abnormalItems,...(r.normalItems||[])].find(x=>x.name===activeMetric);return item?{date:new Date(r.createdAt).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'}),value:item.value,source:r.sourceFile}:null}).filter((x):x is {date:string;value:number;source:string}=>Boolean(x)).reverse(),[history,activeMetric]);
  return <div className="space-y-5"><PageTitle title="宠物报告智能识别" subtitle={`拍摄或上传检查报告，为 ${profile.name} 提取异常项并生成动态护理计划`} action={<button onClick={back} className="rounded-xl border border-[#d7e2dc] bg-white px-3 py-2 text-sm">返回档案</button>}/>
    <Card className="border-[#d9e5dd] bg-[#f7fbf8] p-4"><div className="flex gap-3 text-sm leading-6 text-[#52685b]"><ShieldCheck className="mt-0.5 shrink-0 text-[#2d7657]" size={20}/><p><b>安全解析原则：</b>异常按报告自身参考范围标记。系统提供风险提示与就医沟通清单，不凭单张报告确诊疾病，也不会自行给出药物剂量。</p></div></Card>
    <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><div className="space-y-4"><Card className="p-5"><SectionTitle>1. 先告诉AI当前情况</SectionTitle><div className="grid grid-cols-2 gap-2">{([['undiagnosed','尚未确诊'],['diagnosed','已有兽医诊断']] as const).map(([id,label])=><button key={id} onClick={()=>setDiagnosisStatus(id)} className={`rounded-xl border px-3 py-3 text-sm font-semibold ${diagnosisStatus===id?'border-[#31795b] bg-[#eaf5ee] text-[#256a4d]':'border-[#dce5df] text-[#66776e]'}`}>{label}</button>)}</div><label className="mt-4 block text-xs font-semibold text-[#52665b]">宠物现在有什么不舒服？</label><textarea value={symptoms} onChange={e=>setSymptoms(e.target.value)} rows={3} placeholder="例如：食欲下降、呕吐2次、精神差、饮水增多、尿量减少……" className="mt-2 w-full resize-y rounded-xl border border-[#d5e0d9] p-3 text-sm leading-6 outline-none focus:border-[#347b5e]"/><p className="mt-2 text-xs leading-5 text-[#7d8b83]">没有诊断也可以使用。AI会解释报告和风险，但最终诊断仍由兽医结合检查确认。</p></Card><Card className="p-5"><SectionTitle>2. 拍照或上传报告</SectionTitle><div className="grid grid-cols-2 gap-3"><button onClick={()=>inputRef.current?.click()} className="flex min-h-28 flex-col items-center justify-center rounded-xl bg-[#287656] text-white"><Camera size={27}/><b className="mt-2 text-sm">拍摄报告</b><span className="mt-1 text-[11px] text-white/75">手机可直接调用相机</span></button><button onClick={()=>inputRef.current?.click()} className="flex min-h-28 flex-col items-center justify-center rounded-xl border border-[#c9dbd0] bg-[#f5faf7] text-[#286d51]"><Upload size={25}/><b className="mt-2 text-sm">选择文件</b><span className="mt-1 text-[11px] text-[#71847a]">JPG / PNG / PDF</span></button></div><input ref={inputRef} type="file" accept="image/*,.pdf" capture="environment" className="hidden" onChange={e=>upload(e.target.files?.[0])}/>{previewUrl&&<img src={previewUrl} alt="待识别的宠物报告" className="mt-3 max-h-56 w-full rounded-xl border border-[#dce5df] object-contain"/>}<label className="mt-4 block text-xs font-semibold text-[#52665b]">报告类型</label><select value={type} onChange={e=>setType(e.target.value as ReportType)} className="mt-2 w-full rounded-xl border border-[#d5e0d9] bg-white px-3 py-2.5 text-sm">{REPORT_TYPES.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><p className="mt-3 text-xs leading-5 text-[#7d8b83]">静态版会载入文件并等待OCR文字核对；接入扣子OCR后，此步骤可自动回填。</p></Card>
      <Card className="p-5"><SectionTitle>3. 核对识别文字</SectionTitle><textarea value={text} onChange={e=>setText(e.target.value)} rows={9} placeholder="OCR识别内容会出现在这里；也可以直接粘贴报告文字，需包含项目、数值、单位和参考范围。" className="w-full resize-y rounded-xl border border-[#d5e0d9] p-3 text-sm leading-6 outline-none focus:border-[#347b5e]"/><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>analyze()} disabled={!text.trim()||loading} className="flex items-center justify-center gap-2 rounded-xl bg-[#287656] px-3 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-[#aebcb4]">{loading?<LoaderCircle className="animate-spin" size={17}/>:<ClipboardPaste size={17}/>}生成解读</button><button onClick={()=>{setText(REPORT_DEMO_TEXT);analyze(REPORT_DEMO_TEXT,'示例-犬生化报告')}} className="rounded-xl border border-[#cadbd1] bg-white px-3 py-2.5 text-sm font-semibold text-[#2b6d52]">体验示例</button></div></Card>
    </div><div className="space-y-4">{!result?<EmptyState/>:<><RiskSummary result={result}/>{!result.needsOcr&&<><ResultFacts result={result}/><InferencePanel result={result}/><Card className="p-5"><SectionTitle>需要和兽医讨论</SectionTitle><div className="grid gap-2 sm:grid-cols-3">{result.veterinarianDiscussion.map((x,i)=><div key={x} className="rounded-xl bg-[#f5f8f6] p-3 text-sm leading-6"><b className="mr-2 text-[#2a7455]">{i+1}</b>{x}</div>)}</div></Card><Card className="p-5"><SectionTitle>📋 3. 每日监护方案 <Pill>按本次状态生成</Pill></SectionTitle><div className="grid gap-3 lg:grid-cols-3">{grouped.map(x=><div key={x.period} className={`rounded-xl p-4 ${x.period.includes('立即')?'bg-[#fff0ed]':'bg-[#f4f8f5]'}`}><b className={x.period.includes('立即')?'text-[#a33f37]':'text-[#275f48]'}>{x.period.includes('立即')?'⚠️ 4. '+x.period:x.period}</b><ul className="mt-2 space-y-2 text-sm leading-5 text-[#5d6d64]">{x.actions.map(a=><li key={a}>· {a}</li>)}</ul></div>)}</div><p className="mt-4 text-xs leading-5 text-[#78867e]">方案会随新报告、体重、食欲、饮水、排尿和症状记录重新生成。仅供参考，请遵医嘱；不能替代兽医诊断和处方。</p></Card></>}<button onClick={save} disabled={result.needsOcr} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#245f48] py-3 font-semibold text-white disabled:bg-[#adb9b2]"><Archive size={18}/>{saved?'已存入当前宠物档案':'存入当前宠物档案'}</button></>}</div></div>
    <Card className="p-5"><SectionTitle>已存报告 <span className="text-xs font-normal text-[#7d8b83]">仅保存在本机 · {history.length} 份</span></SectionTitle>{history.length?<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{history.map(x=><button key={x.id} onClick={()=>{setResult(x);setSaved(true)}} className="flex items-center gap-3 rounded-xl border border-[#e0e7e3] p-3 text-left"><History size={18} className="shrink-0 text-[#39785e]"/><span className="min-w-0"><b className="block truncate text-sm">{x.sourceFile}</b><small className="text-[#78877f]">{x.reportTypeLabel} · {x.abnormalItems.length}项异常</small></span></button>)}</div>:<p className="text-sm text-[#7e8b84]">还没有存档报告。完成解析后可保存到 {profile.name} 的健康档案。</p>}</Card>
    <Card className="p-5"><div className="mb-3 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-bold text-[#254536]">连续报告指标趋势</h2><p className="mt-1 text-xs text-[#77867e]">来自当前宠物已保存报告，同名且同单位的指标才适合直接比较。</p></div><select value={activeMetric} onChange={e=>setTrendMetric(e.target.value)} className="rounded-xl border border-[#d5e0d9] bg-white px-3 py-2 text-sm">{metricNames.length?metricNames.map(x=><option key={x}>{x}</option>):<option>暂无指标</option>}</select></div>{trendData.length>=2?<div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={trendData}><CartesianGrid stroke="#edf2ef" vertical={false}/><XAxis dataKey="date" axisLine={false} tickLine={false} fontSize={11}/><YAxis axisLine={false} tickLine={false} fontSize={11}/><Tooltip/><Line dataKey="value" type="monotone" stroke="#2c7657" strokeWidth={2.5} dot={{r:4}}/></LineChart></ResponsiveContainer></div>:<div className="grid min-h-32 place-items-center rounded-xl bg-[#f5f8f6] text-center text-sm leading-6 text-[#7b8981]">同一指标至少保存2次报告后生成曲线。<br/>当前已找到 {trendData.length} 个“{activeMetric||'未选择'}”数据点。</div>}</Card>
    <Card className="p-5"><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="flex items-center gap-2 font-bold text-[#254536]"><Library size={18}/>医院病例参考模板</h2><p className="mt-1 text-xs leading-5 text-[#78877f]">根据您提供的13页医院资料去身份化整理；点击即可载入并查看系统如何判读。</p></div><div className="flex gap-2">{(['all','猫','犬'] as const).map(x=><button key={x} onClick={()=>setCaseFilter(x)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${caseFilter===x?'bg-[#287656] text-white':'bg-[#eef3f0] text-[#53685c]'}`}>{x==='all'?'全部':x}</button>)}</div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{REPORT_CASE_LIBRARY.filter(x=>caseFilter==='all'||x.species===caseFilter).map(item=><button key={item.id} onClick={()=>{setType(item.type);setText(item.text);setResult(analyzeReportText(withContext(item.text),item.title,item.type));setSaved(false);window.scrollTo({top:0,behavior:'smooth'})}} className="rounded-xl border border-[#dfe7e2] bg-white p-4 text-left transition-colors hover:border-[#81af96] hover:bg-[#f7fbf8]"><div className="flex items-center justify-between gap-2"><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${item.species==='猫'?'bg-[#e8f1f8] text-[#3e6e8b]':'bg-[#fff0d8] text-[#8b5b1b]'}`}>{item.species}</span><span className="text-[10px] text-[#89958e]">来源 {item.sourceCount} 页</span></div><b className="mt-3 block text-sm leading-5">{item.title}</b><p className="mt-2 text-xs leading-5 text-[#6c7b73]">{item.summary}</p><span className="mt-3 inline-block text-xs font-semibold text-[#287052]">载入解析 →</span></button>)}</div><div className="mt-4 rounded-xl bg-[#fff8eb] p-3 text-xs leading-5 text-[#796342]"><b>重要边界：</b>这些模板用于识别同类报告结构和风险组合，不是用旧病例替新宠物下诊断。新报告仍必须读取其自己的物种、单位、参考范围、症状和时间趋势。</div></Card>
    <Card className="p-5"><SectionTitle>可识别报告知识模板</SectionTitle><div className="grid gap-3 sm:grid-cols-2">{REPORT_TEMPLATE_LIBRARY.map(x=><details key={x.type} className="rounded-xl border border-[#e0e7e3] p-4"><summary className="flex cursor-pointer list-none items-center justify-between font-semibold">{x.type}<ChevronDown size={17}/></summary><p className="mt-3 text-sm leading-6 text-[#63736a]">字段：{x.fields}</p><p className="mt-1 text-xs leading-5 text-[#8a7161]">判读边界：{x.caution}</p></details>)}</div><details className="mt-3 rounded-xl bg-[#f4f7f5] p-4"><summary className="cursor-pointer text-sm font-semibold">扣子系统提示词（部署配置）</summary><pre className="mt-3 whitespace-pre-wrap text-xs leading-5 text-[#56675e]">{COZE_REPORT_SYSTEM_PROMPT}</pre></details></Card>
  </div>;
}

function EmptyState(){return <Card className="grid min-h-[420px] place-items-center p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#e4f1e9] text-[#2c7657]"><FileScan size={26}/></span><h2 className="mt-4 font-bold">等待检查报告</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#75837b]">上传报告后核对OCR文字，系统将展示异常指标、定性结果、风险分层、就医沟通事项和今天的护理计划。</p></div></Card>}
function RiskSummary({result}:{result:MedicalReportAnalysis}){const meta=riskMeta[result.riskLevel];return <Card className={`p-5 ${meta.classes}`}><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 shrink-0"/><div><div className="flex flex-wrap items-center gap-2"><b className="text-lg">📊 1. 报告摘要 · {meta.label}</b><Pill tone={result.riskLevel==='urgent'?'red':result.riskLevel==='warning'?'amber':'green'}>{result.reportTypeLabel}</Pill><span className="text-xs">识别可信度 {Math.round(result.confidence*100)}%</span></div><p className="mt-2 text-sm leading-6">{result.summary}</p>{result.needsOcr&&<p className="mt-3 text-xs font-semibold">请先使用OCR插件提取文字，或把报告文字粘贴到左侧后再生成医学解读。</p>}</div></div></Card>}
function InferencePanel({result}:{result:MedicalReportAnalysis}){const items=result.riskInferences||[];return <Card className="p-5"><SectionTitle>🔍 2. 慢性病风险推断 <Pill tone="amber">不是确诊</Pill></SectionTitle>{items.length?<div className="space-y-3">{items.map(x=><div key={x.title} className="rounded-xl border border-[#ead9b6] bg-[#fffaf0] p-4"><div className="flex items-center justify-between gap-3"><b>{x.title}</b><span className="rounded-full bg-[#f5dfae] px-2 py-1 text-xs font-semibold text-[#815919]">{x.confidence}置信度</span></div><p className="mt-2 text-sm leading-6 text-[#665c49]"><b>当前证据：</b>{x.evidence}</p><p className="mt-1 text-sm leading-6 text-[#756b59]"><b>还缺什么：</b>{x.missingEvidence}</p></div>)}</div>:<p className="rounded-xl bg-[#f4f7f5] p-4 text-sm leading-6 text-[#66766d]">当前报告没有形成足够明确的慢性病异常组合。单项正常或异常都不能排除/确诊疾病，建议结合症状和连续复查。</p>}</Card>}
function ResultFacts({result}:{result:MedicalReportAnalysis}){const normal=result.normalItems||[];return <Card className="p-5"><SectionTitle>报告事实与异常标记 <span className="text-xs font-normal text-[#78867e]">{result.sourceFile}</span></SectionTitle>{normal.length>0&&<div className="mb-4"><p className="mb-2 text-sm font-semibold text-[#286e50]">这些项目目前在报告参考范围内</p><div className="flex flex-wrap gap-2">{normal.map(x=><span key={`${x.name}${x.value}`} className="rounded-lg bg-[#edf8f1] px-3 py-2 text-xs text-[#286e50]">✓ {x.name} {x.value} {x.unit}</span>)}</div></div>}<p className="mb-2 text-sm font-semibold text-[#a33d36]">需要重点关注的项目</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{result.abnormalItems.map(x=><div key={`${x.name}${x.value}`} className="rounded-xl border border-[#efc6c0] bg-[#fff5f3] p-3"><div className="flex justify-between"><b className="text-sm">{x.name}</b><span className="text-xs font-semibold text-[#b04941]">{x.direction}</span></div><p className="mt-1 text-xl font-bold text-[#a33d36]">{x.value} <small className="text-xs font-normal">{x.unit}</small></p><p className="mt-1 text-xs text-[#846b66]">参考范围 {x.reference}</p></div>)}{result.qualitativeResults.map(x=><div key={x.name} className={`rounded-xl border p-3 ${x.result==='阳性'||x.result==='检出'?'border-[#efc6c0] bg-[#fff5f3]':'border-[#cfe2d6] bg-[#f3faf5]'}`}><b className="text-sm">{x.name}</b><p className={`mt-2 font-bold ${x.result==='阳性'||x.result==='检出'?'text-[#a33d36]':'text-[#286e50]'}`}>{x.result}</p></div>)}</div>{!result.abnormalItems.length&&!result.qualitativeResults.length&&<p className="text-sm text-[#7c8982]">没有解析到带参考范围的数值或定性结果，请核对OCR文字格式。</p>}{result.possibleConcerns.length>0&&<div className="mt-4 rounded-xl bg-[#fff9ed] p-4"><b className="text-sm text-[#80571d]">为什么需要关注、下一步怎么改善</b>{result.possibleConcerns.map(x=><p key={x} className="mt-2 text-sm leading-6 text-[#75664f]">{x}</p>)}</div>}</Card>}
