'use client';
import { useMemo,useState } from 'react';
import { Cat,Check,Dog,Search } from 'lucide-react';
import { searchBreeds,type Species } from '@/lib/pet-breeds';
import type { PetProfile } from './pet-profile-context';

const breedStatuses=['纯种','疑似纯种','混血/串串','中华田园犬','中华田园猫','土猫','其他','不确定'];
const dogTraits=['短鼻犬','长背短腿犬','大型深胸犬','巨型犬','小型犬'];
function bodySize(species:Species,weight:number){
 if(species==='cat') return weight<3?'小体型':weight<5.5?'标准体型':weight<8?'大体型':'巨型';
 return weight<5?'迷你型':weight<10?'小型':weight<15?'中小型':weight<25?'中型':weight<40?'大型':'巨型';
}
function bcsLabel(score:number){return score<=3?'偏瘦':score<=5?'理想':score<=7?'超重':'肥胖';}

export function OnboardingModal({onComplete}:{onComplete:(profile:PetProfile)=>void}){
 const [species,setSpecies]=useState<Species>('cat'); const [query,setQuery]=useState(''); const [breed,setBreed]=useState(''); const [custom,setCustom]=useState('');
 const [breedStatus,setBreedStatus]=useState('不确定'); const [ancestry,setAncestry]=useState(''); const [bcs,setBcs]=useState(5); const [traits,setTraits]=useState<string[]>([]);
 const [form,setForm]=useState({name:'',gender:'公',age:'',weight:'',disease:'',stage:'',hospital:'',doctor:''});
 const results=useMemo(()=>searchBreeds(species,query).slice(0,48),[species,query]); const finalBreed=breed==='其他/自定义'?custom.trim():(breed||query.trim()); const weight=Number(form.weight); const size=weight>0?bodySize(species,weight):'等待填写体重';
 const missing=[!form.name.trim()&&'宠物名字',!form.age.trim()&&'年龄',!(weight>0)&&'有效体重',!finalBreed&&'具体品种'].filter(Boolean) as string[];
 const valid=missing.length===0;
 const toggleTrait=(trait:string)=>setTraits(x=>x.includes(trait)?x.filter(v=>v!==trait):[...x,trait]);
 const submit=()=>{if(!valid)return;onComplete({id:`pet-${Date.now()}`,name:form.name.trim(),species,breed:finalBreed,breedStatus,suspectedAncestry:ancestry.trim(),age:form.age.trim(),gender:form.gender,weight,bodySize:size,bcs,bodyTraits:traits,disease:form.disease.trim(),stage:form.stage.trim(),diagnosedAt:'',hospital:form.hospital.trim(),doctor:form.doctor.trim(),careAuthorization:'not_connected',insuranceProvider:'',insurancePolicyNo:'',insuranceStatus:'not_configured',avatar:species==='cat'?'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=500&q=90':'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=500&q=90'});};
 return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-[#173529]/55 backdrop-blur-sm sm:items-center sm:p-6"><div className="max-h-[95vh] w-full max-w-4xl overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl sm:p-7"><div className="mb-6"><span className="text-xs font-semibold text-[#2c7758]">首次使用 · 综合健康建档</span><h1 className="mt-2 text-2xl font-bold text-[#1d4232]">不只看品种，更要看真实身体状况</h1><p className="mt-2 text-sm leading-6 text-[#718078]">品种仅作背景信息。系统将结合实测体重、体型、BCS体况和身体结构进行风险分层。</p></div>
 <div className="mb-5 grid grid-cols-2 gap-2">{([['cat','猫咪',Cat],['dog','狗狗',Dog]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>{setSpecies(id);setBreed('');setQuery('');setTraits([])}} className={`flex items-center justify-center gap-2 rounded-xl border py-3 font-semibold ${species===id?'border-[#2e7b5c] bg-[#e7f3eb] text-[#256d4e]':'border-[#dfe7e2] text-[#6f7d75]'}`}><Icon size={19}/>{label}</button>)}</div>
 <div className="grid gap-4 sm:grid-cols-2"><Field label="宠物名字"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="例如：团仔" className="input"/></Field><Field label="性别"><select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})} className="input bg-white"><option>公</option><option>母</option><option>未知</option></select></Field><Field label="年龄"><input value={form.age} onChange={e=>setForm({...form,age:e.target.value})} placeholder="例如：5岁2个月" className="input"/></Field><Field label="当前实测体重（kg）"><input value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})} inputMode="decimal" placeholder="必须填写，例如：4.8" className="input"/></Field></div>
 <div className="mt-5 rounded-2xl border border-[#dce7e0] p-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="血统/品种状态"><select value={breedStatus} onChange={e=>setBreedStatus(e.target.value)} className="input bg-white">{breedStatuses.filter(x=>!x.includes('犬')||species==='dog').filter(x=>!['中华田园猫','土猫'].includes(x)||species==='cat').map(x=><option key={x}>{x}</option>)}</select></Field>{breedStatus==='混血/串串'&&<Field label="疑似血统（选填）"><input value={ancestry} onChange={e=>setAncestry(e.target.value)} placeholder="例如：疑似拉布拉多混田园犬" className="input"/></Field>}</div><label className="mt-4 block text-sm font-semibold">具体品种</label><div className="relative mt-2"><Search className="absolute left-3 top-3 text-[#819087]" size={17}/><input value={query} onChange={e=>{setQuery(e.target.value);setBreed('')}} placeholder="可直接填写，也可搜索后点击候选项" className="input pl-10"/></div><p className="mt-2 text-xs text-[#718078]">输入完整品种名称即可保存；点击下方候选项可快速确认。</p><div className="mt-2 max-h-40 overflow-y-auto rounded-xl bg-[#f8faf9] p-2"><div className="grid grid-cols-2 gap-1 sm:grid-cols-4">{results.map(item=><button key={item.name} onClick={()=>{setBreed(item.name);setQuery(item.name==='其他/自定义'?'':item.name)}} className={`flex items-center justify-between rounded-lg px-2.5 py-2 text-left text-xs ${breed===item.name?'bg-[#def0e5] font-semibold text-[#23694c]':'hover:bg-white'}`}>{item.name}{breed===item.name&&<Check size={14}/>}</button>)}</div></div>{breed==='其他/自定义'&&<input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="填写具体品种或混种信息" className="input mt-2"/>}{finalBreed&&<div className="mt-2 flex items-center gap-2 rounded-lg bg-[#eaf6ee] px-3 py-2 text-xs font-semibold text-[#276b4f]"><Check size={14}/>已确认品种：{finalBreed}</div>}</div>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#f1f7f3] p-4"><p className="text-sm font-semibold">系统自动体型</p><p className="mt-2 text-2xl font-bold text-[#276f52]">{size}</p><p className="mt-1 text-xs leading-5 text-[#718078]">根据当前实测体重自动判断，不按品种平均体重推测。</p></div><div className="rounded-2xl bg-[#fff8ea] p-4"><div className="flex justify-between"><p className="text-sm font-semibold">BCS 体况评分</p><b className="text-[#9a671f]">{bcs}/9 · {bcsLabel(bcs)}</b></div><input type="range" min="1" max="9" value={bcs} onChange={e=>setBcs(Number(e.target.value))} className="mt-4 w-full accent-[#2d7859]"/><div className="mt-1 flex justify-between text-[10px] text-[#83775f]"><span>1 偏瘦</span><span>5 理想</span><span>9 肥胖</span></div></div></div>
 {species==='dog'&&<div className="mt-5"><p className="text-sm font-semibold">身体结构标签（可多选）</p><div className="mt-2 flex flex-wrap gap-2">{dogTraits.map(x=><button key={x} onClick={()=>toggleTrait(x)} className={`rounded-full border px-3 py-2 text-xs ${traits.includes(x)?'border-[#2d7859] bg-[#e3f1e8] font-semibold text-[#276b4f]':'border-[#dce4df]'}`}>{x}</button>)}</div><p className="mt-2 text-xs text-[#7b8981]">用于提示呼吸、麻醉、椎间盘、胃扭转、关节等结构相关风险，不用于诊断。</p></div>}
 <div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="已确诊慢病（选填）"><input value={form.disease} onChange={e=>setForm({...form,disease:e.target.value})} placeholder="没有确诊请留空" className="input"/></Field><Field label="医院确认的分期/状态（选填）"><input value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})} placeholder="没有结果请留空" className="input"/></Field><Field label="主治医院（选填，仅记录你填写的名称）"><input value={form.hospital} onChange={e=>setForm({...form,hospital:e.target.value})} className="input"/></Field><Field label="主治医生（选填）"><input value={form.doctor} onChange={e=>setForm({...form,doctor:e.target.value})} className="input"/></Field></div>
 <div className="mt-5 rounded-xl bg-[#fff4ef] p-3 text-xs leading-5 text-[#805247]">药物剂量必须由兽医依据当前体重、诊断、化验指标和处方计算；系统不会仅凭品种或体型自行开药。</div>{!valid&&<div className="mt-4 rounded-xl border border-[#efd4a5] bg-[#fffaf1] p-3 text-sm text-[#8a5d20]">还需要填写：{missing.join('、')}</div>}<button disabled={!valid} onClick={submit} className="mt-4 w-full rounded-xl bg-[#287656] py-3 font-semibold text-white disabled:cursor-not-allowed disabled:bg-[#b8c5be]">{valid?'保存综合档案，开始使用':`请补全 ${missing.length} 项必填信息`}</button></div></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-semibold">{label}{children}</label>}
