'use client';
import { useEffect,useMemo,useState } from 'react';
import { ArrowLeft,CheckCircle2,ClipboardCheck,Database,FileCheck2,LineChart,Plus,ShieldCheck,Stethoscope } from 'lucide-react';
import { loadDailyCheckins } from '@/lib/daily-checkins';
import { usePetProfile } from './pet-profile-context';
import { Card,PageTitle,Pill,SectionTitle } from './ui';

type OutcomeRecord={id:string;petId:string;disease:'CKD'|'糖尿病';metric:string;baseline:string;followup:string;intervention:string;startDate:string;reviewDate:string;doctorConfirmed:boolean;conclusion:string;createdAt:string};
const storeKey=(petId:string)=>`petcare-outcome-loop:${petId}`;
const metricOptions={CKD:['体重 kg','主动饮水 ml/日','肌酐 CREA','SDMA','血磷 P','尿蛋白 UP/C'],糖尿病:['体重 kg','空腹血糖','餐后血糖','最低血糖','果糖胺','每日饮水 ml']} as const;

export function OutcomeLoopWorkspace({back}:{back:()=>void}){
 const {profile}=usePetProfile();const initialDisease=/糖尿病/.test(profile.disease)?'糖尿病':'CKD';
 const [records,setRecords]=useState<OutcomeRecord[]>([]);const [saved,setSaved]=useState(false);const [form,setForm]=useState({disease:initialDisease as 'CKD'|'糖尿病',metric:metricOptions[initialDisease][0] as string,baseline:'',followup:'',intervention:'',startDate:new Date().toISOString().slice(0,10),reviewDate:'',doctorConfirmed:false});
 useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem(storeKey(profile.id))||'[]'))}catch{setRecords([])}},[profile.id]);
 const checkins=useMemo(()=>loadDailyCheckins(profile.id),[profile.id,records.length]);const hasHomeData=checkins.length>0;let reports=0;try{reports=JSON.parse(localStorage.getItem(`petcare-medical-reports:${profile.id}`)||'[]').length}catch{reports=0}
 const conclusion=compare(form.baseline,form.followup,form.metric);
 const save=()=>{if(!form.baseline.trim()||!form.followup.trim()||!form.intervention.trim()||!form.reviewDate)return;const item:OutcomeRecord={id:`outcome-${Date.now()}`,petId:profile.id,...form,conclusion,createdAt:new Date().toISOString()};const next=[item,...records];setRecords(next);localStorage.setItem(storeKey(profile.id),JSON.stringify(next));setSaved(true)};
 const stages=[[Database,'家庭数据',hasHomeData,`${checkins.length}条打卡`],[LineChart,'趋势整理',hasHomeData,'按时间比较'],[ClipboardCheck,'护理干预',records.length>0,`${records.length}次记录`],[Stethoscope,'医生确认',records.some(x=>x.doctorConfirmed),'需执业兽医'],[FileCheck2,'复查结果',reports>0||records.length>0,`${reports}份报告`]] as const;
 return <div className="space-y-5"><PageTitle title="护理效果闭环" subtitle="先做好CKD与糖尿病：记录、执行、复查、验证" action={<button onClick={back} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm"><ArrowLeft size={16}/>返回</button>}/>
 <Card className="border-[#d5e4da] bg-[#f5faf7] p-4 text-sm leading-6 text-[#52675b]"><ShieldCheck className="mr-2 inline text-[#287656]" size={18}/><b>数据原则：</b>单次变化不能证明护理有效。只有记录时间、干预内容、复查结果和医生确认都完整，才可用于个体效果评估；未经授权的数据不得提供给医院、品牌或保险机构。</Card>
 <div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{stages.map(([Icon,label,done,detail],i)=><Card key={label} className={`p-3 ${done?'border-[#9ec9ae] bg-[#f0f9f3]':'bg-[#f5f6f5]'}`}><div className="flex items-center justify-between"><Icon size={18} className={done?'text-[#287656]':'text-[#87918c]'}/><span className="text-[10px] text-[#87918c]">{i+1}/5</span></div><b className="mt-2 block text-xs">{label}</b><p className="mt-1 text-[10px] text-[#718078]">{detail}</p></Card>)}</div>
 {saved&&<Card className="border-[#9bc9ad] bg-[#eff9f3] p-4 text-sm"><CheckCircle2 className="mr-2 inline text-[#287656]" size={18}/>效果记录已存档。结论只描述数值变化，不自动认定病情改善或改变分期。</Card>}
 <div className="grid gap-4 lg:grid-cols-[1fr_380px]"><Card className="p-5 sm:p-6"><SectionTitle>新增干预—结果记录</SectionTitle><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">病种<select value={form.disease} onChange={e=>{const d=e.target.value as 'CKD'|'糖尿病';setForm({...form,disease:d,metric:metricOptions[d][0]})}} className="input bg-white"><option>CKD</option><option>糖尿病</option></select></label><label className="text-sm font-semibold">观察指标<select value={form.metric} onChange={e=>setForm({...form,metric:e.target.value})} className="input bg-white">{metricOptions[form.disease].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">干预前数值<input value={form.baseline} onChange={e=>setForm({...form,baseline:e.target.value})} placeholder="按报告原单位填写" className="input"/></label><label className="text-sm font-semibold">复查数值<input value={form.followup} onChange={e=>setForm({...form,followup:e.target.value})} placeholder="按相同单位填写" className="input"/></label><label className="text-sm font-semibold">开始日期<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} className="input"/></label><label className="text-sm font-semibold">复查日期<input type="date" value={form.reviewDate} onChange={e=>setForm({...form,reviewDate:e.target.value})} className="input"/></label></div><label className="mt-4 block text-sm font-semibold">期间执行了什么<textarea value={form.intervention} onChange={e=>setForm({...form,intervention:e.target.value})} rows={4} placeholder="例如：按医生方案更换处方饮食、每日记录饮水；不要填写未经医生确认的自行加药" className="input resize-y leading-6"/></label><label className="mt-4 flex items-start gap-3 rounded-xl bg-[#f4f7f5] p-3 text-sm"><input type="checkbox" checked={form.doctorConfirmed} onChange={e=>setForm({...form,doctorConfirmed:e.target.checked})} className="mt-1"/><span><b>该干预方案或结果已经医生确认</b><small className="mt-1 block leading-5 text-[#718078]">未确认也可记录，但不会标记为临床验证数据。</small></span></label><div className="mt-4 rounded-xl bg-[#f7f9f8] p-3 text-sm">系统比较：<b>{conclusion}</b></div><button onClick={save} disabled={!form.baseline.trim()||!form.followup.trim()||!form.intervention.trim()||!form.reviewDate} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#287656] py-3 font-semibold text-white disabled:bg-gray-300"><Plus size={18}/>存档效果记录</button></Card>
 <Card className="h-fit p-5"><SectionTitle>历史闭环记录</SectionTitle>{records.length?<div className="space-y-3">{records.map(x=><div key={x.id} className="rounded-xl bg-[#f5f8f6] p-3"><div className="flex justify-between gap-2"><b className="text-sm">{x.disease} · {x.metric}</b><Pill tone={x.doctorConfirmed?'green':'amber'}>{x.doctorConfirmed?'医生已确认':'用户记录'}</Pill></div><p className="mt-2 text-sm">{x.baseline} → {x.followup}</p><p className="mt-1 text-xs leading-5 text-[#708078]">{x.startDate} 至 {x.reviewDate}<br/>{x.conclusion}</p></div>)}</div>:<p className="py-10 text-center text-sm leading-6 text-[#7a8880]">还没有效果记录。先建立基线，再按相同单位录入复查结果。</p>}</Card></div></div>;
}

function compare(a:string,b:string,metric:string){const before=Number(a),after=Number(b);if(!Number.isFinite(before)||!Number.isFinite(after))return'已记录前后结果，含非数字内容，需医生人工解释';if(before===after)return`${metric}与基线相同`;const pct=before===0?null:Math.abs((after-before)/before*100);return`${metric}${after>before?'上升':'下降'}${pct===null?'':` ${pct.toFixed(1)}%`}；变化不等于改善或恶化，需结合指标方向、病种和医生判断`}
