'use client';
import { useEffect,useRef,useState } from 'react';
import { AlertTriangle,Camera,CheckCircle2,Droplets,Plus,Stethoscope } from 'lucide-react';
import { loadSymptomLogs,saveSymptomLog,type SymptomLog,type SymptomLogType } from '@/lib/symptom-logs';
import { usePetProfile } from './pet-profile-context';
import { Card,Pill,SectionTitle } from './ui';

const localDateTime=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)};
const empty=(type:SymptomLogType)=>({type,occurredAt:localDateTime(),title:type==='water_urine'?'多饮多尿观察':type==='vomiting'?'呕吐记录':'',description:'',waterMl:'',waterCompared:'与平时相近',urineClumpCount:'',urineClumpCm:'',urineCompared:'与平时相近',vomitCount:'',vomitAppearance:'未选择',mealRelation:'不确定'});

export function SymptomLogWorkspace(){
 const {profile}=usePetProfile();const [logs,setLogs]=useState<SymptomLog[]>([]);const [mode,setMode]=useState<SymptomLogType>('general');const [form,setForm]=useState(empty('general'));const [photos,setPhotos]=useState<{name:string;data:string}[]>([]);const [saved,setSaved]=useState<SymptomLog|null>(null);const [saveError,setSaveError]=useState('');const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{setLogs(loadSymptomLogs(profile.id));setSaved(null);setMode('general');setForm(empty('general'));setPhotos([])},[profile.id]);
 const changeMode=(next:SymptomLogType)=>{setMode(next);setForm(empty(next));setPhotos([]);setSaved(null)};
 const readPhotos=(files:FileList|null)=>{for(const file of Array.from(files||[]).slice(0,3-photos.length)){if(file.size>300_000){setSaveError(`${file.name}超过300KB，请压缩后重新添加。`);continue}const reader=new FileReader();reader.onload=()=>setPhotos(x=>[...x,{name:file.name,data:String(reader.result)}].slice(0,3));reader.readAsDataURL(file)}};
 const n=(value:string)=>value.trim()===''?null:Number(value);
 const save=()=>{setSaveError('');const recordedAt=new Date().toISOString();const log:SymptomLog={id:`symptom-${Date.now()}`,petId:profile.id,type:mode,occurredAt:new Date(form.occurredAt).toISOString(),recordedAt,title:form.title.trim()||({general:'新症状',water_urine:'多饮多尿观察',vomiting:'呕吐记录'} as const)[mode],description:form.description.trim(),waterMl:n(form.waterMl),waterCompared:form.waterCompared,urineClumpCount:n(form.urineClumpCount),urineClumpCm:n(form.urineClumpCm),urineCompared:form.urineCompared,vomitCount:n(form.vomitCount),vomitAppearance:form.vomitAppearance,mealRelation:form.mealRelation,photoDataUrls:photos.map(x=>x.data),photoNames:photos.map(x=>x.name)};try{setLogs(saveSymptomLog(log));setSaved(log);setPhotos([])}catch{setSaveError('本机存储空间不足，记录尚未保存。请减少照片数量或压缩照片后重试。')}};
 const risk=saved&&(saved.urineCompared==='无尿/排不出'||(saved.vomitCount||0)>=3);
 return <div className="grid gap-4 lg:grid-cols-[1fr_360px]"><div>{saved?<Card className={`mb-4 p-5 ${risk?'border-[#e5aaa3] bg-[#fff3f1]':'border-[#9bc9ad] bg-[#f1faf4]'}`}><div className="flex gap-3">{risk?<AlertTriangle className="shrink-0 text-[#a7443e]"/>:<CheckCircle2 className="shrink-0 text-[#287656]"/>}<div><b>{risk?'症状已存档，存在紧急风险':'症状日志已存档'}</b><p className="mt-1 text-sm leading-6">档案编号：{saved.id} · {new Date(saved.occurredAt).toLocaleString('zh-CN',{hour12:false})}</p>{risk&&<p className="mt-2 text-sm font-semibold text-[#9b403a]">无尿/排不出或短时间反复呕吐应立即联系宠物医院，不等待趋势分析。</p>}</div></div></Card>:null}<Card className="p-5 sm:p-6"><SectionTitle>记录新症状</SectionTitle><div className="grid grid-cols-3 gap-2">{([['general','其他症状',Stethoscope],['water_urine','多饮多尿',Droplets],['vomiting','呕吐',AlertTriangle]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>changeMode(id)} className={`flex min-h-20 flex-col items-center justify-center gap-2 rounded-xl border text-sm ${mode===id?'border-[#3b8063] bg-[#e7f3ec] font-semibold text-[#226849]':'border-[#dce5df] bg-white text-[#66756d]'}`}><Icon size={19}/>{label}</button>)}</div><label className="mt-5 block text-sm font-semibold">发生时间<input type="datetime-local" value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})} className="input"/></label><label className="mt-4 block text-sm font-semibold">记录标题<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="例如：晚上精神突然变差" className="input"/></label>
{mode==='water_urine'&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><NumberField label="24小时主动饮水" value={form.waterMl} set={v=>setForm({...form,waterMl:v})} unit="ml"/><SelectField label="与平时饮水相比" value={form.waterCompared} set={v=>setForm({...form,waterCompared:v})} values={['明显减少','略少','与平时相近','略多','明显增加','不确定']}/><NumberField label="24小时尿团数量" value={form.urineClumpCount} set={v=>setForm({...form,urineClumpCount:v})} unit="个"/><NumberField label="平均尿团直径" value={form.urineClumpCm} set={v=>setForm({...form,urineClumpCm:v})} unit="cm"/><SelectField label="与平时排尿相比" value={form.urineCompared} set={v=>setForm({...form,urineCompared:v})} values={['明显减少','略少','与平时相近','略多','明显增多','无尿/排不出','不确定']}/></div>}
{mode==='vomiting'&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><NumberField label="本次/当天呕吐次数" value={form.vomitCount} set={v=>setForm({...form,vomitCount:v})} unit="次"/><SelectField label="呕吐物外观" value={form.vomitAppearance} set={v=>setForm({...form,vomitAppearance:v})} values={['未选择','未消化食物','透明液体','白色泡沫','黄色/黄绿色液体','鲜血','咖啡渣样','其他']}/><SelectField label="与进食关系" value={form.mealRelation} set={v=>setForm({...form,mealRelation:v})} values={['进食前','进食后立即','进食后1-3小时','与进食无明显关系','不确定']}/></div>}
<label className="mt-4 block text-sm font-semibold">详细描述<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={5} placeholder="记录持续时间、精神、食欲、排尿姿势、呕吐内容和其他变化" className="input resize-y leading-6"/></label><div className="mt-4"><button onClick={()=>fileRef.current?.click()} className="flex items-center gap-2 rounded-xl border border-[#cbdad2] bg-[#f6faf7] px-4 py-2.5 text-sm font-semibold text-[#2d7053]"><Camera size={18}/>添加照片（最多3张）</button><input ref={fileRef} type="file" accept="image/*" capture="environment" multiple className="hidden" onChange={e=>readPhotos(e.target.files)}/><p className="mt-2 text-xs text-[#7b8981]">单张不超过300KB；照片只保存在当前设备。过大的照片不会添加。</p>{photos.length>0&&<div className="mt-3 grid grid-cols-3 gap-2">{photos.map((x,i)=><div key={`${x.name}-${i}`} className="relative"><img src={x.data} alt={x.name} className="aspect-square w-full rounded-lg object-cover"/><button onClick={()=>setPhotos(p=>p.filter((_,j)=>j!==i))} className="absolute right-1 top-1 rounded-full bg-black/65 px-2 py-1 text-[10px] text-white">移除</button></div>)}</div>}</div>{saveError&&<p className="mt-3 rounded-xl bg-[#fff2ef] p-3 text-sm text-[#9a423c]">{saveError}</p>}<button onClick={save} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#287656] py-3 font-semibold text-white"><Plus size={18}/>存档症状记录</button></Card></div>
<Card className="h-fit overflow-hidden"><div className="border-b border-[#e3eae6] p-4"><div className="flex items-center justify-between"><b>症状历史</b><Pill>{logs.length}条</Pill></div></div><div className="max-h-[760px] space-y-2 overflow-y-auto p-3">{logs.length?logs.map(log=><div key={log.id} className="rounded-xl bg-[#f5f8f6] p-3"><div className="flex justify-between gap-2"><b className="text-sm">{log.title}</b><Pill tone={log.type==='vomiting'?'amber':'green'}>{log.type==='water_urine'?'多饮多尿':log.type==='vomiting'?'呕吐':'其他'}</Pill></div><p className="mt-1 text-xs text-[#74827a]">{new Date(log.occurredAt).toLocaleString('zh-CN',{hour12:false})}</p>{log.type==='water_urine'&&<p className="mt-2 text-xs leading-5">饮水 {log.waterMl??'未填'}ml · 尿团 {log.urineClumpCount??'未填'}个 · 平均 {log.urineClumpCm??'未填'}cm</p>}{log.type==='vomiting'&&<p className="mt-2 text-xs leading-5">呕吐 {log.vomitCount??'未填'}次 · {log.vomitAppearance} · {log.mealRelation}</p>}{log.description&&<p className="mt-2 text-sm leading-5 text-[#5f7067]">{log.description}</p>}{log.photoDataUrls.length>0&&<div className="mt-2 flex gap-2">{log.photoDataUrls.map((src,i)=><img key={i} src={src} alt={log.photoNames[i]||'症状照片'} className="size-16 rounded-lg object-cover"/>)}</div>}</div>):<p className="p-8 text-center text-sm leading-6 text-[#7b8981]">还没有症状日志。记录后会按发生时间排列。</p>}</div></Card></div>;
}
function NumberField({label,value,set,unit}:{label:string;value:string;set:(v:string)=>void;unit:string}){return <label className="rounded-xl bg-[#f5f8f6] p-3 text-xs font-semibold text-[#66776e]">{label}<span className="mt-2 flex items-center gap-2"><input value={value} onChange={e=>set(e.target.value)} inputMode="decimal" placeholder="未测量" className="min-w-0 w-full rounded-lg border border-[#d7e2dc] bg-white px-3 py-2 text-base text-[#2c493b]"/>{unit}</span></label>}
function SelectField({label,value,set,values}:{label:string;value:string;set:(v:string)=>void;values:string[]}){return <label className="rounded-xl bg-[#f5f8f6] p-3 text-xs font-semibold text-[#66776e]">{label}<select value={value} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d7e2dc] bg-white px-3 py-2 text-sm text-[#2c493b]">{values.map(x=><option key={x}>{x}</option>)}</select></label>}
